#coding: utf-8


import matplotlib
matplotlib.use('Qt5Agg')
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, QEvent, pyqtSignal
from PyQt5.QtWidgets import (QWidget, QLineEdit, QLabel, QPushButton, QSizePolicy, QMessageBox)
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas , NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
import numpy as np
from math import *
from fenetrage1 import cohen_sutherland
from fenetrage2 import sutherland_hodgman


class PlotCanvas(FigureCanvas):
	def __init__(self, parent = None, width = 5, height = 4, dpi = 100):
		fig = Figure(figsize = (width, height), dpi= dpi)
		self.ax1 = fig.add_subplot(121)
		self.ax2 = fig.add_subplot(122)
		FigureCanvas.__init__(self, fig)
		self.setParent(parent)
		FigureCanvas.setSizePolicy(self, QSizePolicy.Expanding, QSizePolicy.Expanding)
		FigureCanvas.updateGeometry(self)

	def plot(self, p1, p2, r):
		self.ax1.cla()
		self.ax2.cla()
		self.ax1.set_title('Before')
		self.ax2.set_title('After')
		cohen_sutherland(self.ax1, self.ax2, p1, p2, r)
		self.draw()

	def plot_poly(self, poly1, poly2):
		self.ax1.cla()
		self.ax2.cla()
		self.ax1.set_title('Before')
		self.ax2.set_title('After')
		sutherland_hodgman(self.ax1, self.ax2, poly1, poly2)
		self.draw()

class inputFocusFilter(QObject):
	focusIn = pyqtSignal(object)

	def eventFilter(self, widget, event):
		if event.type() == QEvent.FocusIn and isinstance(widget, QLineEdit):
			self.focusIn.emit(widget)
		return super(inputFocusFilter, self).eventFilter(widget, event)

class MyApplication(QtWidgets.QApplication):
	def __init__(self, *arg, **kwarg):
		super(MyApplication, self).__init__(*arg, **kwarg)

		self._input_focus_widget = None

		self.event_filter = inputFocusFilter()
		self.event_filter.focusIn.connect(self.setInputFocusWidget)
		self.installEventFilter(self.event_filter)

	def setInputFocusWidget(self, widget):
		self._input_focus_widget = widget

	def inputFocusWidget(self):
		return self._input_focus_widget


class Ui_ClippingMainWindow(object):
	def __init__(self):
		self.new = False
	def setupUi(self, ClippingMainWindow):
		ClippingMainWindow.setObjectName("ClippingMainWindow")
		ClippingMainWindow.resize(1024, 768)
		ClippingMainWindow.setMinimumSize(QtCore.QSize(1024, 768))
		ClippingMainWindow.setMaximumSize(QtCore.QSize(1024, 768))
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("cg.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		ClippingMainWindow.setWindowIcon(icon)		
		self.centralwidget = QtWidgets.QWidget(ClippingMainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.clipping_menu = QtWidgets.QGroupBox(self.centralwidget)
		self.clipping_menu.setGeometry(QtCore.QRect(0, 0, 200, 768))
		self.clipping_menu.setMinimumSize(QtCore.QSize(200, 768))
		self.clipping_menu.setMaximumSize(QtCore.QSize(200, 768))
		self.clipping_menu.setStyleSheet("*{\n"
"    background-color: #87ffcd;\n"
"    margin: 0;\n"
"    width: 100%;\n"
"    height: 100%\n"
"}\n"
"QPushButton {\n"
"    min-width: 100%;\n"
"    margin: 0;\n"
"    padding: 10px;\n"
"    font: 75 16px \"MS Shell Dlg 2\";\n"
"    height: auto;\n"
"    outline: None; \n"
"    border: None\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5c49d6;\n"
"    color: #fff\n"
"}")
		self.clipping_menu.setTitle("")
		self.clipping_menu.setObjectName("clipping_menu")
		self.select_segment = QtWidgets.QPushButton(self.clipping_menu)
		self.select_segment.setGeometry(QtCore.QRect(0, 15, 200, 60))
		self.select_segment.setMinimumSize(QtCore.QSize(120, 60))
		self.select_segment.setMaximumSize(QtCore.QSize(200, 60))
		self.select_segment.setStyleSheet("")
		self.select_segment.setObjectName("select_segment")
		self.select_polygone = QtWidgets.QPushButton(self.clipping_menu)
		self.select_polygone.setGeometry(QtCore.QRect(0, 75, 200, 60))
		self.select_polygone.setMinimumSize(QtCore.QSize(120, 60))
		self.select_polygone.setMaximumSize(QtCore.QSize(200, 60))
		self.select_polygone.setStyleSheet("")
		self.select_polygone.setObjectName("select_polygone")
		self.select_quit = QtWidgets.QPushButton(self.clipping_menu)
		self.select_quit.setGeometry(QtCore.QRect(0, 600, 200, 60))
		self.select_quit.setMinimumSize(QtCore.QSize(120, 60))
		self.select_quit.setMaximumSize(QtCore.QSize(200, 60))
		self.select_quit.setStyleSheet("")
		self.select_quit.setObjectName("select_quit")
		self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
		self.stackedWidget.setGeometry(QtCore.QRect(200, 0, 824, 768))
		self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.stackedWidget.setObjectName("stackedWidget")
		self.segment_page = QtWidgets.QWidget()
		self.segment_page.setObjectName("segment_page")
		#segment plotting
		self.segment_graph_box = QtWidgets.QGroupBox(self.segment_page)
		self.segment_graph_box.setGeometry(QtCore.QRect(60, 220, 691, 511))
		segment_graph = PlotCanvas(self.segment_graph_box, width=6.9, height=5.1, dpi=100)
		segment_toolbar = NavigationToolbar(segment_graph, self.segment_graph_box)
		segment_toolbar.move(80, 0)		
		self.segment_graph_box.setStyleSheet("border: none;\n")
		self.groupBox_3 = QtWidgets.QGroupBox(self.segment_page)
		self.groupBox_3.setGeometry(QtCore.QRect(60, 20, 571, 180))
		self.groupBox_3.setStyleSheet("background-color:#abff8d;\n"
"border-radius: 5px;")
		self.groupBox_3.setTitle("")
		self.groupBox_3.setObjectName("groupBox_3")
		self.rectangle_box = QtWidgets.QGroupBox(self.groupBox_3)
		self.rectangle_box.setGeometry(QtCore.QRect(15, 20, 271, 130))
		self.rectangle_box.setMinimumSize(QtCore.QSize(271, 130))
		self.rectangle_box.setMaximumSize(QtCore.QSize(271, 130))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(11)
		font.setBold(False)
		font.setWeight(50)
		self.rectangle_box.setFont(font)
		self.rectangle_box.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"    border-right: 1px solid #333;\n"
"}")
		self.rectangle_box.setObjectName("rectangle_box")
		self.label = QtWidgets.QLabel(self.rectangle_box)
		self.label.setGeometry(QtCore.QRect(5, 40, 55, 30))
		self.label.setMinimumSize(QtCore.QSize(55, 30))
		self.label.setMaximumSize(QtCore.QSize(55, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		self.label.setFont(font)
		self.label.setObjectName("label")
		self.label_2 = QtWidgets.QLabel(self.rectangle_box)
		self.label_2.setGeometry(QtCore.QRect(5, 80, 55, 30))
		self.label_2.setMinimumSize(QtCore.QSize(55, 30))
		self.label_2.setMaximumSize(QtCore.QSize(55, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		self.label_2.setFont(font)
		self.label_2.setObjectName("label_2")
		self.label_3 = QtWidgets.QLabel(self.rectangle_box)
		self.label_3.setGeometry(QtCore.QRect(140, 40, 55, 30))
		self.label_3.setMinimumSize(QtCore.QSize(55, 30))
		self.label_3.setMaximumSize(QtCore.QSize(55, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		self.label_3.setFont(font)
		self.label_3.setObjectName("label_3")
		self.label_4 = QtWidgets.QLabel(self.rectangle_box)
		self.label_4.setGeometry(QtCore.QRect(140, 80, 55, 30))
		self.label_4.setMinimumSize(QtCore.QSize(55, 30))
		self.label_4.setMaximumSize(QtCore.QSize(55, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		self.label_4.setFont(font)
		self.label_4.setObjectName("label_4")
		self.xmin_input = QtWidgets.QLineEdit(self.rectangle_box)
		self.xmin_input.setGeometry(QtCore.QRect(60, 45, 60, 24))
		self.xmin_input.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.xmin_input.setObjectName("xmin_input")
		self.xmax_input = QtWidgets.QLineEdit(self.rectangle_box)
		self.xmax_input.setGeometry(QtCore.QRect(200, 45, 60, 24))
		self.xmax_input.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.xmax_input.setObjectName("xmax_input")
		self.ymax_input = QtWidgets.QLineEdit(self.rectangle_box)
		self.ymax_input.setGeometry(QtCore.QRect(200, 85, 60, 24))
		self.ymax_input.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ymax_input.setObjectName("ymax_input")
		self.ymin_input = QtWidgets.QLineEdit(self.rectangle_box)
		self.ymin_input.setGeometry(QtCore.QRect(60, 85, 60, 24))
		self.ymin_input.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ymin_input.setObjectName("ymin_input")
		self.segment_box = QtWidgets.QGroupBox(self.groupBox_3)
		self.segment_box.setGeometry(QtCore.QRect(300, 20, 251, 130))
		self.segment_box.setMinimumSize(QtCore.QSize(251, 130))
		self.segment_box.setMaximumSize(QtCore.QSize(251, 130))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(11)
		font.setBold(False)
		font.setWeight(50)
		self.segment_box.setFont(font)
		self.segment_box.setObjectName("segment_box")
		self.label_5 = QtWidgets.QLabel(self.segment_box)
		self.label_5.setGeometry(QtCore.QRect(10, 40, 30, 30))
		self.label_5.setMinimumSize(QtCore.QSize(30, 30))
		self.label_5.setMaximumSize(QtCore.QSize(30, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		self.label_5.setFont(font)
		self.label_5.setObjectName("label_5")
		self.label_7 = QtWidgets.QLabel(self.segment_box)
		self.label_7.setGeometry(QtCore.QRect(130, 40, 10, 30))
		self.label_7.setMinimumSize(QtCore.QSize(10, 30))
		self.label_7.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		self.label_7.setFont(font)
		self.label_7.setObjectName("label_7")
		self.segment_p1_x = QtWidgets.QLineEdit(self.segment_box)
		self.segment_p1_x.setGeometry(QtCore.QRect(45, 45, 65, 24))
		self.segment_p1_x.setMinimumSize(QtCore.QSize(65, 0))
		self.segment_p1_x.setMaximumSize(QtCore.QSize(65, 24))
		self.segment_p1_x.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.segment_p1_x.setObjectName("segment_p1_x")
		self.segment_p1_y = QtWidgets.QLineEdit(self.segment_box)
		self.segment_p1_y.setGeometry(QtCore.QRect(150, 45, 60, 24))
		self.segment_p1_y.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.segment_p1_y.setObjectName("segment_p1_y")
		self.label_9 = QtWidgets.QLabel(self.segment_box)
		self.label_9.setGeometry(QtCore.QRect(220, 40, 55, 30))
		self.label_9.setMinimumSize(QtCore.QSize(55, 30))
		self.label_9.setMaximumSize(QtCore.QSize(55, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		self.label_9.setFont(font)
		self.label_9.setObjectName("label_9")
		self.segment_p2_x = QtWidgets.QLineEdit(self.segment_box)
		self.segment_p2_x.setGeometry(QtCore.QRect(45, 85, 65, 24))
		self.segment_p2_x.setMinimumSize(QtCore.QSize(65, 0))
		self.segment_p2_x.setMaximumSize(QtCore.QSize(65, 24))
		self.segment_p2_x.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.segment_p2_x.setObjectName("segment_p2_x")
		self.label_6 = QtWidgets.QLabel(self.segment_box)
		self.label_6.setGeometry(QtCore.QRect(10, 80, 30, 30))
		self.label_6.setMinimumSize(QtCore.QSize(30, 30))
		self.label_6.setMaximumSize(QtCore.QSize(30, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		self.label_6.setFont(font)
		self.label_6.setObjectName("label_6")
		self.label_10 = QtWidgets.QLabel(self.segment_box)
		self.label_10.setGeometry(QtCore.QRect(220, 80, 55, 30))
		self.label_10.setMinimumSize(QtCore.QSize(55, 30))
		self.label_10.setMaximumSize(QtCore.QSize(55, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		self.label_10.setFont(font)
		self.label_10.setObjectName("label_10")
		self.label_8 = QtWidgets.QLabel(self.segment_box)
		self.label_8.setGeometry(QtCore.QRect(130, 80, 10, 30))
		self.label_8.setMinimumSize(QtCore.QSize(10, 30))
		self.label_8.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		self.label_8.setFont(font)
		self.label_8.setObjectName("label_8")
		self.segment_p2_y = QtWidgets.QLineEdit(self.segment_box)
		self.segment_p2_y.setGeometry(QtCore.QRect(150, 85, 60, 24))
		self.segment_p2_y.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.segment_p2_y.setObjectName("segment_p2_y")
		self.segment_keyboard_btn = QtWidgets.QPushButton(self.segment_page)
		self.segment_keyboard_btn.setGeometry(QtCore.QRect(650, 150, 100, 40))
		self.segment_keyboard_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.segment_keyboard_btn.setText("")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/newPrefix/keyboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		self.segment_keyboard_btn.setIcon(icon)
		self.segment_keyboard_btn.setIconSize(QtCore.QSize(100, 50))
		self.segment_keyboard_btn.setObjectName("segment_keyboard_btn")
		self.segment_keyboard = None
		self.segment_keyboard = self.keyboardf(self.segment_page, self.segment_keyboard)
		self.segment_ok = QtWidgets.QPushButton(self.segment_page)
		self.segment_ok.clicked.connect(lambda: self.segment_graph_plot(segment_graph))
		self.segment_ok.setGeometry(QtCore.QRect(650, 100, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.segment_ok.setFont(font)
		self.segment_ok.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.segment_ok.setObjectName("segment_ok")
		self.stackedWidget.addWidget(self.segment_page)
		self.polygone_page = QtWidgets.QWidget()
		self.polygone_page.setObjectName("polygone_page")
		#polygone plotting
		self.polygone_graph_box = QtWidgets.QGroupBox(self.polygone_page)
		self.polygone_graph_box.setGeometry(QtCore.QRect(60, 220, 691, 511))
		polygone_graph = PlotCanvas(self.polygone_graph_box, width=6.9, height=5.1, dpi=100)
		polygone_toolbar = NavigationToolbar(polygone_graph, self.polygone_graph_box)
		polygone_toolbar.move(80, 0)		
		self.polygone_graph_box.setStyleSheet("border: none;\n")
		self.polygone_ok = QtWidgets.QPushButton(self.polygone_page)
		self.polygone_ok.clicked.connect(lambda: self.polygone_graph_plot(polygone_graph))
		self.polygone_ok.setGeometry(QtCore.QRect(650, 130, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.polygone_ok.setFont(font)
		self.polygone_ok.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.polygone_ok.setObjectName("polygone_ok")
		self.polygone_keyboard_btn = QtWidgets.QPushButton(self.polygone_page)
		self.polygone_keyboard_btn.setGeometry(QtCore.QRect(650, 180, 100, 40))
		self.polygone_keyboard_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.polygone_keyboard_btn.setText("")
		self.polygone_keyboard_btn.setIcon(icon)
		self.polygone_keyboard_btn.setIconSize(QtCore.QSize(100, 50))
		self.polygone_keyboard_btn.setObjectName("polygone_keyboard_btn")
		self.groupBox_4 = QtWidgets.QGroupBox(self.polygone_page)
		self.groupBox_4.setGeometry(QtCore.QRect(60, 20, 571, 201))
		self.groupBox_4.setMinimumSize(QtCore.QSize(571, 201))
		self.groupBox_4.setMaximumSize(QtCore.QSize(571, 201))
		self.groupBox_4.setStyleSheet("background-color:#abff8d;\n"
"border-radius: 5px;")
		self.groupBox_4.setTitle("")
		self.groupBox_4.setObjectName("groupBox_4")
		self.groupBox = QtWidgets.QGroupBox(self.groupBox_4)
		self.groupBox.setGeometry(QtCore.QRect(10, 10, 270, 190))
		self.groupBox.setMinimumSize(QtCore.QSize(270, 190))
		self.groupBox.setMaximumSize(QtCore.QSize(270, 190))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(11)
		self.groupBox.setFont(font)
		self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"    border-right: 1px solid #333;\n"
"}")
		self.groupBox.setObjectName("groupBox")
		self.fenetrage_p1p1 = QtWidgets.QLineEdit(self.groupBox)
		self.fenetrage_p1p1.setGeometry(QtCore.QRect(30, 35, 65, 24))
		self.fenetrage_p1p1.setMinimumSize(QtCore.QSize(65, 0))
		self.fenetrage_p1p1.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p1p1.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p1p1.setText("")
		self.fenetrage_p1p1.setObjectName("fenetrage_p1p1")
		self.label_11 = QtWidgets.QLabel(self.groupBox)
		self.label_11.setGeometry(QtCore.QRect(0, 30, 22, 30))
		self.label_11.setMinimumSize(QtCore.QSize(22, 30))
		self.label_11.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_11.setFont(font)
		self.label_11.setObjectName("label_11")
		self.label_13 = QtWidgets.QLabel(self.groupBox)
		self.label_13.setGeometry(QtCore.QRect(100, 30, 10, 30))
		self.label_13.setMinimumSize(QtCore.QSize(10, 30))
		self.label_13.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_13.setFont(font)
		self.label_13.setObjectName("label_13")
		self.fenetrage_p1p2 = QtWidgets.QLineEdit(self.groupBox)
		self.fenetrage_p1p2.setGeometry(QtCore.QRect(169, 35, 65, 24))
		self.fenetrage_p1p2.setMinimumSize(QtCore.QSize(65, 24))
		self.fenetrage_p1p2.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p1p2.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p1p2.setText("")
		self.fenetrage_p1p2.setObjectName("fenetrage_p1p2")
		self.label_14 = QtWidgets.QLabel(self.groupBox)
		self.label_14.setGeometry(QtCore.QRect(239, 30, 10, 30))
		self.label_14.setMinimumSize(QtCore.QSize(10, 30))
		self.label_14.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_14.setFont(font)
		self.label_14.setObjectName("label_14")
		self.label_12 = QtWidgets.QLabel(self.groupBox)
		self.label_12.setGeometry(QtCore.QRect(140, 30, 22, 30))
		self.label_12.setMinimumSize(QtCore.QSize(22, 30))
		self.label_12.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_12.setFont(font)
		self.label_12.setObjectName("label_12")
		self.fenetrage_p1p3 = QtWidgets.QLineEdit(self.groupBox)
		self.fenetrage_p1p3.setGeometry(QtCore.QRect(29, 75, 65, 24))
		self.fenetrage_p1p3.setMinimumSize(QtCore.QSize(65, 0))
		self.fenetrage_p1p3.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p1p3.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p1p3.setText("")
		self.fenetrage_p1p3.setObjectName("fenetrage_p1p3")
		self.label_15 = QtWidgets.QLabel(self.groupBox)
		self.label_15.setGeometry(QtCore.QRect(99, 70, 10, 30))
		self.label_15.setMinimumSize(QtCore.QSize(10, 30))
		self.label_15.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_15.setFont(font)
		self.label_15.setObjectName("label_15")
		self.label_16 = QtWidgets.QLabel(self.groupBox)
		self.label_16.setGeometry(QtCore.QRect(0, 70, 22, 30))
		self.label_16.setMinimumSize(QtCore.QSize(22, 30))
		self.label_16.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_16.setFont(font)
		self.label_16.setObjectName("label_16")
		self.fenetrage_p1p4 = QtWidgets.QLineEdit(self.groupBox)
		self.fenetrage_p1p4.setGeometry(QtCore.QRect(169, 75, 65, 24))
		self.fenetrage_p1p4.setMinimumSize(QtCore.QSize(65, 24))
		self.fenetrage_p1p4.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p1p4.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p1p4.setText("")
		self.fenetrage_p1p4.setObjectName("fenetrage_p1p4")
		self.label_111 = QtWidgets.QLabel(self.groupBox)
		self.label_111.setGeometry(QtCore.QRect(140, 70, 22, 30))
		self.label_111.setMinimumSize(QtCore.QSize(22, 30))
		self.label_111.setMaximumSize(QtCore.QSize(22, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_111.setFont(font)
		self.label_111.setObjectName("label_111")
		self.label_131 = QtWidgets.QLabel(self.groupBox)
		self.label_131.setGeometry(QtCore.QRect(239, 70, 10, 30))
		self.label_131.setMinimumSize(QtCore.QSize(10, 30))
		self.label_131.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_131.setFont(font)
		self.label_131.setObjectName("label_131")
		self.fenetrage_p1p5 = QtWidgets.QLineEdit(self.groupBox)
		self.fenetrage_p1p5.setGeometry(QtCore.QRect(29, 115, 65, 24))
		self.fenetrage_p1p5.setMinimumSize(QtCore.QSize(65, 0))
		self.fenetrage_p1p5.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p1p5.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p1p5.setText("")
		self.fenetrage_p1p5.setObjectName("fenetrage_p1p5")
		self.label_151 = QtWidgets.QLabel(self.groupBox)
		self.label_151.setGeometry(QtCore.QRect(99, 110, 10, 30))
		self.label_151.setMinimumSize(QtCore.QSize(10, 30))
		self.label_151.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_151.setFont(font)
		self.label_151.setObjectName("label_151")
		self.label_161 = QtWidgets.QLabel(self.groupBox)
		self.label_161.setGeometry(QtCore.QRect(0, 110, 22, 30))
		self.label_161.setMinimumSize(QtCore.QSize(22, 30))
		self.label_161.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_161.setFont(font)
		self.label_161.setObjectName("label_161")
		self.fenetrage_p1p6 = QtWidgets.QLineEdit(self.groupBox)
		self.fenetrage_p1p6.setGeometry(QtCore.QRect(169, 115, 65, 24))
		self.fenetrage_p1p6.setMinimumSize(QtCore.QSize(65, 24))
		self.fenetrage_p1p6.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p1p6.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p1p6.setText("")
		self.fenetrage_p1p6.setObjectName("fenetrage_p1p6")
		self.label_112 = QtWidgets.QLabel(self.groupBox)
		self.label_112.setGeometry(QtCore.QRect(140, 110, 22, 30))
		self.label_112.setMinimumSize(QtCore.QSize(22, 30))
		self.label_112.setMaximumSize(QtCore.QSize(22, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_112.setFont(font)
		self.label_112.setObjectName("label_112")
		self.label_132 = QtWidgets.QLabel(self.groupBox)
		self.label_132.setGeometry(QtCore.QRect(239,110, 10, 30))
		self.label_132.setMinimumSize(QtCore.QSize(10, 30))
		self.label_132.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_132.setFont(font)
		self.label_132.setObjectName("label_132")
		self.fenetrage_p1p7 = QtWidgets.QLineEdit(self.groupBox)
		self.fenetrage_p1p7.setGeometry(QtCore.QRect(29, 150, 65, 24))
		self.fenetrage_p1p7.setMinimumSize(QtCore.QSize(65, 0))
		self.fenetrage_p1p7.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p1p7.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p1p7.setText("")
		self.fenetrage_p1p7.setObjectName("fenetrage_p1p7")
		self.label_152 = QtWidgets.QLabel(self.groupBox)
		self.label_152.setGeometry(QtCore.QRect(99, 145, 10, 30))
		self.label_152.setMinimumSize(QtCore.QSize(10, 30))
		self.label_152.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_152.setFont(font)
		self.label_152.setObjectName("label_152")
		self.label_162 = QtWidgets.QLabel(self.groupBox)
		self.label_162.setGeometry(QtCore.QRect(0, 145, 22, 30))
		self.label_162.setMinimumSize(QtCore.QSize(22, 30))
		self.label_162.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_162.setFont(font)
		self.label_162.setObjectName("label_162")
		self.fenetrage_p1p8 = QtWidgets.QLineEdit(self.groupBox)
		self.fenetrage_p1p8.setGeometry(QtCore.QRect(169, 150, 65, 24))
		self.fenetrage_p1p8.setMinimumSize(QtCore.QSize(65, 24))
		self.fenetrage_p1p8.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p1p8.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p1p8.setText("")
		self.fenetrage_p1p8.setObjectName("fenetrage_p1p8")
		self.label_113 = QtWidgets.QLabel(self.groupBox)
		self.label_113.setGeometry(QtCore.QRect(140, 145, 22, 30))
		self.label_113.setMinimumSize(QtCore.QSize(22, 30))
		self.label_113.setMaximumSize(QtCore.QSize(22, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_113.setFont(font)
		self.label_113.setObjectName("label_113")
		self.label_133 = QtWidgets.QLabel(self.groupBox)
		self.label_133.setGeometry(QtCore.QRect(239,145, 10, 30))
		self.label_133.setMinimumSize(QtCore.QSize(10, 30))
		self.label_133.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_133.setFont(font)
		self.label_133.setObjectName("label_133")
		self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_4)
		self.groupBox_2.setGeometry(QtCore.QRect(290, 10, 270, 190))
		self.groupBox_2.setMinimumSize(QtCore.QSize(270, 190))
		self.groupBox_2.setMaximumSize(QtCore.QSize(270, 190))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(11)
		self.groupBox_2.setFont(font)
		self.groupBox_2.setObjectName("groupBox_2")
		self.fenetrage_p2p1 = QtWidgets.QLineEdit(self.groupBox_2)
		self.fenetrage_p2p1.setGeometry(QtCore.QRect(30, 35, 65, 24))
		self.fenetrage_p2p1.setMinimumSize(QtCore.QSize(65, 0))
		self.fenetrage_p2p1.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p2p1.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p2p1.setText("")
		self.fenetrage_p2p1.setObjectName("fenetrage_p2p1")
		self.label_21 = QtWidgets.QLabel(self.groupBox_2)
		self.label_21.setGeometry(QtCore.QRect(0, 30, 22, 30))
		self.label_21.setMinimumSize(QtCore.QSize(22, 30))
		self.label_21.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_21.setFont(font)
		self.label_21.setObjectName("label_21")
		self.label_23 = QtWidgets.QLabel(self.groupBox_2)
		self.label_23.setGeometry(QtCore.QRect(100, 30, 10, 30))
		self.label_23.setMinimumSize(QtCore.QSize(10, 30))
		self.label_23.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_23.setFont(font)
		self.label_23.setObjectName("label_23")
		self.fenetrage_p2p2 = QtWidgets.QLineEdit(self.groupBox_2)
		self.fenetrage_p2p2.setGeometry(QtCore.QRect(169, 35, 65, 24))
		self.fenetrage_p2p2.setMinimumSize(QtCore.QSize(65, 24))
		self.fenetrage_p2p2.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p2p2.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p2p2.setText("")
		self.fenetrage_p2p2.setObjectName("fenetrage_p2p2")
		self.label_24 = QtWidgets.QLabel(self.groupBox_2)
		self.label_24.setGeometry(QtCore.QRect(239, 30, 10, 30))
		self.label_24.setMinimumSize(QtCore.QSize(10, 30))
		self.label_24.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_24.setFont(font)
		self.label_24.setObjectName("label_24")
		self.label_22 = QtWidgets.QLabel(self.groupBox_2)
		self.label_22.setGeometry(QtCore.QRect(140, 30, 22, 30))
		self.label_22.setMinimumSize(QtCore.QSize(22, 30))
		self.label_22.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_22.setFont(font)
		self.label_22.setObjectName("label_22")
		self.fenetrage_p2p3 = QtWidgets.QLineEdit(self.groupBox_2)
		self.fenetrage_p2p3.setGeometry(QtCore.QRect(29, 75, 65, 24))
		self.fenetrage_p2p3.setMinimumSize(QtCore.QSize(65, 0))
		self.fenetrage_p2p3.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p2p3.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p2p3.setText("")
		self.fenetrage_p2p3.setObjectName("fenetrage_p2p3")
		self.label_25 = QtWidgets.QLabel(self.groupBox_2)
		self.label_25.setGeometry(QtCore.QRect(99, 70, 10, 30))
		self.label_25.setMinimumSize(QtCore.QSize(10, 30))
		self.label_25.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_25.setFont(font)
		self.label_25.setObjectName("label_25")
		self.label_26 = QtWidgets.QLabel(self.groupBox_2)
		self.label_26.setGeometry(QtCore.QRect(0, 70, 22, 30))
		self.label_26.setMinimumSize(QtCore.QSize(22, 30))
		self.label_26.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_26.setFont(font)
		self.label_26.setObjectName("label_26")
		self.fenetrage_p2p4 = QtWidgets.QLineEdit(self.groupBox_2)
		self.fenetrage_p2p4.setGeometry(QtCore.QRect(169, 75, 65, 24))
		self.fenetrage_p2p4.setMinimumSize(QtCore.QSize(65, 24))
		self.fenetrage_p2p4.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p2p4.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p2p4.setText("")
		self.fenetrage_p2p4.setObjectName("fenetrage_p2p4")
		self.label_211 = QtWidgets.QLabel(self.groupBox_2)
		self.label_211.setGeometry(QtCore.QRect(140, 70, 22, 30))
		self.label_211.setMinimumSize(QtCore.QSize(22, 30))
		self.label_211.setMaximumSize(QtCore.QSize(22, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_211.setFont(font)
		self.label_211.setObjectName("label_211")
		self.label_231 = QtWidgets.QLabel(self.groupBox_2)
		self.label_231.setGeometry(QtCore.QRect(239, 70, 10, 30))
		self.label_231.setMinimumSize(QtCore.QSize(10, 30))
		self.label_231.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_231.setFont(font)
		self.label_231.setObjectName("label_231")
		self.fenetrage_p2p5 = QtWidgets.QLineEdit(self.groupBox_2)
		self.fenetrage_p2p5.setGeometry(QtCore.QRect(29, 115, 65, 24))
		self.fenetrage_p2p5.setMinimumSize(QtCore.QSize(65, 0))
		self.fenetrage_p2p5.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p2p5.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p2p5.setText("")
		self.fenetrage_p2p5.setObjectName("fenetrage_p2p5")
		self.label_251 = QtWidgets.QLabel(self.groupBox_2)
		self.label_251.setGeometry(QtCore.QRect(99, 110, 10, 30))
		self.label_251.setMinimumSize(QtCore.QSize(10, 30))
		self.label_251.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_251.setFont(font)
		self.label_251.setObjectName("label_251")
		self.label_261 = QtWidgets.QLabel(self.groupBox_2)
		self.label_261.setGeometry(QtCore.QRect(0, 110, 22, 30))
		self.label_261.setMinimumSize(QtCore.QSize(22, 30))
		self.label_261.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_261.setFont(font)
		self.label_261.setObjectName("label_261")
		self.fenetrage_p2p6 = QtWidgets.QLineEdit(self.groupBox_2)
		self.fenetrage_p2p6.setGeometry(QtCore.QRect(169, 115, 65, 24))
		self.fenetrage_p2p6.setMinimumSize(QtCore.QSize(65, 24))
		self.fenetrage_p2p6.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p2p6.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p2p6.setText("")
		self.fenetrage_p2p6.setObjectName("fenetrage_p2p6")
		self.label_212 = QtWidgets.QLabel(self.groupBox_2)
		self.label_212.setGeometry(QtCore.QRect(140, 110, 22, 30))
		self.label_212.setMinimumSize(QtCore.QSize(22, 30))
		self.label_212.setMaximumSize(QtCore.QSize(22, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_212.setFont(font)
		self.label_212.setObjectName("label_212")
		self.label_232 = QtWidgets.QLabel(self.groupBox_2)
		self.label_232.setGeometry(QtCore.QRect(239,110, 10, 30))
		self.label_232.setMinimumSize(QtCore.QSize(10, 30))
		self.label_232.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_232.setFont(font)
		self.label_232.setObjectName("label_232")
		self.fenetrage_p2p7 = QtWidgets.QLineEdit(self.groupBox_2)
		self.fenetrage_p2p7.setGeometry(QtCore.QRect(29, 150, 65, 24))
		self.fenetrage_p2p7.setMinimumSize(QtCore.QSize(65, 0))
		self.fenetrage_p2p7.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p2p7.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p2p7.setText("")
		self.fenetrage_p2p7.setObjectName("fenetrage_p2p7")
		self.label_252 = QtWidgets.QLabel(self.groupBox_2)
		self.label_252.setGeometry(QtCore.QRect(99, 145, 10, 30))
		self.label_252.setMinimumSize(QtCore.QSize(10, 30))
		self.label_252.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_252.setFont(font)
		self.label_252.setObjectName("label_252")
		self.label_262 = QtWidgets.QLabel(self.groupBox_2)
		self.label_262.setGeometry(QtCore.QRect(0, 145, 22, 30))
		self.label_262.setMinimumSize(QtCore.QSize(22, 30))
		self.label_262.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_262.setFont(font)
		self.label_262.setObjectName("label_262")
		self.fenetrage_p2p8 = QtWidgets.QLineEdit(self.groupBox_2)
		self.fenetrage_p2p8.setGeometry(QtCore.QRect(169, 150, 65, 24))
		self.fenetrage_p2p8.setMinimumSize(QtCore.QSize(65, 24))
		self.fenetrage_p2p8.setMaximumSize(QtCore.QSize(40, 24))
		self.fenetrage_p2p8.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.fenetrage_p2p8.setText("")
		self.fenetrage_p2p8.setObjectName("fenetrage_p2p8")
		self.label_213 = QtWidgets.QLabel(self.groupBox_2)
		self.label_213.setGeometry(QtCore.QRect(140, 145, 22, 30))
		self.label_213.setMinimumSize(QtCore.QSize(22, 30))
		self.label_213.setMaximumSize(QtCore.QSize(22, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_213.setFont(font)
		self.label_213.setObjectName("label_213")
		self.label_233 = QtWidgets.QLabel(self.groupBox_2)
		self.label_233.setGeometry(QtCore.QRect(239,145, 10, 30))
		self.label_233.setMinimumSize(QtCore.QSize(10, 30))
		self.label_233.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_233.setFont(font)
		self.label_233.setObjectName("label_233")
		self.polygone_keyboard = None
		self.polygone_keyboard = self.keyboardf(self.polygone_page, self.polygone_keyboard)
		self.polygone_new_btn = QtWidgets.QPushButton(self.polygone_page)
		self.polygone_new_btn.clicked.connect(self.polygone_pagef)
		self.polygone_new_btn.setGeometry(QtCore.QRect(650, 80, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.polygone_new_btn.setFont(font)
		self.polygone_new_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.polygone_new_btn.setObjectName("polygone_new_btn")
		self.stackedWidget.addWidget(self.polygone_page)
		ClippingMainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(ClippingMainWindow)
		self.stackedWidget.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(ClippingMainWindow)

	def retranslateUi(self, ClippingMainWindow):
		_translate = QtCore.QCoreApplication.translate
		ClippingMainWindow.setWindowTitle(_translate("ClippingMainWindow", "Computer Graphics - clipping"))
		self.select_segment.setText(_translate("ClippingMainWindow", "Fenêtrage d\'un Segment"))
		self.select_segment.clicked.connect(self.segment_pagef)
		self.select_polygone.setText(_translate("ClippingMainWindow", "Fenêtrage d\'un Polygone"))
		self.select_polygone.clicked.connect(self.polygone_pagef)
		self.select_quit.setText(_translate("ClippingMainWindow", "Back"))
		self.select_quit.clicked.connect(ClippingMainWindow.close)
		self.rectangle_box.setTitle(_translate("ClippingMainWindow", "Rectangle"))
		self.label.setText(_translate("ClippingMainWindow", "Xmin ="))
		self.label_2.setText(_translate("ClippingMainWindow", "Ymin = "))
		self.label_3.setText(_translate("ClippingMainWindow", "Xmax ="))
		self.label_4.setText(_translate("ClippingMainWindow", "Ymax ="))
		self.segment_box.setTitle(_translate("ClippingMainWindow", "Segment"))
		self.label_5.setText(_translate("ClippingMainWindow", "P1 ("))
		self.label_7.setText(_translate("ClippingMainWindow", ","))
		self.label_9.setText(_translate("ClippingMainWindow", ")"))
		self.label_6.setText(_translate("ClippingMainWindow", "P2 ("))
		self.label_10.setText(_translate("ClippingMainWindow", ")"))
		self.label_8.setText(_translate("ClippingMainWindow", ","))
		self.segment_ok.setText(_translate("ClippingMainWindow", "OK"))
		self.polygone_ok.setText(_translate("ClippingMainWindow", "OK"))
		self.groupBox.setTitle(_translate("ClippingMainWindow", "Fenetrage de"))
		self.label_11.setText(_translate("ClippingMainWindow", "P1 ("))
		self.label_13.setText(_translate("ClippingMainWindow", ")"))
		self.label_111.setText(_translate("ClippingMainWindow", "P4 ("))
		self.label_131.setText(_translate("ClippingMainWindow", ")"))
		self.label_112.setText(_translate("ClippingMainWindow", "P6 ("))
		self.label_132.setText(_translate("ClippingMainWindow", ")"))
		self.label_161.setText(_translate("ClippingMainWindow", "P5 ("))
		self.label_151.setText(_translate("ClippingMainWindow", ")"))
		self.label_113.setText(_translate("ClippingMainWindow", "P8 ("))
		self.label_133.setText(_translate("ClippingMainWindow", ")"))
		self.label_162.setText(_translate("ClippingMainWindow", "P7 ("))
		self.label_152.setText(_translate("ClippingMainWindow", ")"))
		self.label_14.setText(_translate("ClippingMainWindow", ")"))
		self.label_12.setText(_translate("ClippingMainWindow", "P2 ("))
		self.label_15.setText(_translate("ClippingMainWindow", ")"))
		self.label_16.setText(_translate("ClippingMainWindow", "P3 ("))
		self.groupBox_2.setTitle(_translate("ClippingMainWindow", "Par"))
		self.label_21.setText(_translate("ClippingMainWindow", "P1 ("))
		self.label_23.setText(_translate("ClippingMainWindow", ")"))
		self.label_211.setText(_translate("ClippingMainWindow", "P4 ("))
		self.label_231.setText(_translate("ClippingMainWindow", ")"))
		self.label_212.setText(_translate("ClippingMainWindow", "P6 ("))
		self.label_232.setText(_translate("ClippingMainWindow", ")"))
		self.label_261.setText(_translate("ClippingMainWindow", "P5 ("))
		self.label_251.setText(_translate("ClippingMainWindow", ")"))
		self.label_213.setText(_translate("ClippingMainWindow", "P8 ("))
		self.label_233.setText(_translate("ClippingMainWindow", ")"))
		self.label_262.setText(_translate("ClippingMainWindow", "P7 ("))
		self.label_252.setText(_translate("ClippingMainWindow", ")"))
		self.label_24.setText(_translate("ClippingMainWindow", ")"))
		self.label_22.setText(_translate("ClippingMainWindow", "P2 ("))
		self.label_25.setText(_translate("ClippingMainWindow", ")"))
		self.label_26.setText(_translate("ClippingMainWindow", "P3 ("))
		self.polygone_new_btn.setText(_translate("ClippingMainWindow", "New"))
		self.segment_keyboard_btn.clicked.connect(lambda: self.showorhide(self.segment_keyboard))
		self.polygone_keyboard_btn.clicked.connect(lambda: self.showorhide(self.polygone_keyboard))

	def missing_data_dialog(self, text):
		msg = QMessageBox()
		msg.setIcon(QMessageBox.Warning)
		msg.setText(f"Entrer {text}!!")
		msg.setWindowTitle("Error!")
		msg.setStandardButtons(QMessageBox.Ok)
		msg.exec_()

	def wrong_expr_dialog(self, text):
		msg = QMessageBox()
		msg.setIcon(QMessageBox.Warning)
		msg.setText(f"Expression de {text} est fausse!!")
		msg.setWindowTitle("Error!")
		msg.setStandardButtons(QMessageBox.Ok)
		msg.exec_()

	def normalize_formula(self, formula, text):
		formula = formula.replace('^', '**')
		formula = formula.replace('π', 'pi')
		try:
			formula = eval(formula)
		except Exception:
			self.wrong_expr_dialog(text)
			return None
		return formula

	def normalize_formula_2d(self, formula, text):
		formula =  formula.split(',')
		formula = [formula[i].replace('^', '**').replace('π', 'pi') for i in [0,1]]
		formula  = tuple(formula)
		try:
			formula = [eval(formula[i]) for i in [0,1]]
			formula = tuple(formula)
		except Exception:
			self.wrong_expr_dialog(text)
			return None
		return formula

	def segment_graph_plot(self, segment_graph):
		p1x, p1y, p2x, p2y = self.segment_p1_x.text(), self.segment_p1_y.text(), self.segment_p2_x.text(), self.segment_p2_y.text()
		xmin, xmax, ymin, ymax = self.xmin_input.text(), self.xmax_input.text(), self.ymin_input.text(), self.ymax_input.text()
		if (len(p1x) == 0) or (len(p1y) == 0) or (len(p2x) == 0)  or (len(p2y) == 0) :
			self.missing_data_dialog('les Cordonnées')
			return
		if (len(xmin) == 0) or (len(xmax) == 0) or (len(ymin) == 0)  or (len(ymax) == 0) :
			self.missing_data_dialog('les données du rectangle')
			return
		p1x = self.normalize_formula(p1x, 'p1x')
		p1y = self.normalize_formula(p1y, 'p1y')
		p2x = self.normalize_formula(p2x, 'p2x')
		p2y = self.normalize_formula(p2y, 'p2y')
		xmax = self.normalize_formula(xmax, 'xmax')
		xmin = self.normalize_formula(xmin, 'xmin')
		ymax = self.normalize_formula(ymax, 'ymax')
		ymin = self.normalize_formula(ymin, 'ymin')
		if (p1x != None and p1y != None and p2x != None and p2y != None and xmin != None and xmax != None and ymin != None and ymax != None):
			self.segment_keyboard.setMinimumSize(QtCore.QSize(680, 227))
			self.showorhide(self.segment_keyboard)
			segment_graph.plot((p1x, p1y), (p2x, p2y), (xmin, xmax, ymin, ymax))

	def polygone_graph_plot(self, polygone_graph):
		p11, p12 = self.fenetrage_p1p1.text(), self.fenetrage_p1p2.text()
		p13, p14 = self.fenetrage_p1p3.text(), self.fenetrage_p1p4.text()
		p15, p16 = self.fenetrage_p1p5.text(), self.fenetrage_p1p6.text()
		p17, p18 = self.fenetrage_p1p7.text(), self.fenetrage_p1p8.text()
		if (len(p11) == 0) or (len(p12) == 0) or (len(p13) == 0) :
			self.missing_data_dialog('au moins Poly1P1, Poly1P2, et PolyP3')
			return
		points1 = [p11, p12, p13, p14, p15, p16, p17, p18]
		i = 0
		while i < 9 and len(points1[i]) > 0:
			points1[i] = self.normalize_formula_2d(points1[i], f'p{i+1}')
			i += 1
		if i < 9:
			points1 = points1[:i]
		test = 1
		for j in range(i):
			if points1[j] == None:
				test = 0
				break
		if (test):
			p21, p22 = self.fenetrage_p2p1.text(), self.fenetrage_p2p2.text()
			p23, p24 = self.fenetrage_p2p3.text(), self.fenetrage_p2p4.text()
			p25, p26 = self.fenetrage_p2p5.text(), self.fenetrage_p2p6.text()
			p27, p28 = self.fenetrage_p2p7.text(), self.fenetrage_p2p8.text()
			if (len(p21) == 0) or (len(p22) == 0) or (len(p23) == 0) :
				self.missing_data_dialog('au moins Poly2P1, Poly2P2, et Poly2P3')
				return
			points2 = [p21, p22, p23, p24, p25, p26, p27, p28]
			i = 0
			while i < 9 and len(points2[i]) > 0:
				points2[i] = self.normalize_formula_2d(points2[i], f'p{i+1}')
				i += 1
			if i < 9:
				points2 = points2[:i]
			test2 = 1
			for j in range(i):
				if points2[j] == None:
					test2 = 0
					break
			if test2:
				self.polygone_keyboard.setMinimumSize(QtCore.QSize(680, 227))
				self.showorhide(self.polygone_keyboard)
				poly2 = points1
				poly1 = points2
				polygone_graph.plot_poly(poly1, poly2)

	def clear_all_inputs(self):
		listsMyQLineEdit = self.centralwidget.findChildren(QLineEdit)
		for myQLineEdit in listsMyQLineEdit:
		    myQLineEdit.clear()

	def segment_pagef(self):
		self.stackedWidget.setCurrentIndex(0)
		self.new = True
		self.clear_all_inputs()

	def polygone_pagef(self):
		self.stackedWidget.setCurrentIndex(1)
		self.new = True
		self.clear_all_inputs()
		
	def setFocusOnLast(self):
		widget = QtWidgets.QApplication.instance().inputFocusWidget()
		if widget:
			return widget

	def toinput(self, text, name):
		widget_input = self.setFocusOnLast() if not self.new else None
		self.new = False
		if widget_input is None:
			widget_input = self.fenetrage_p1p1 if (name == self.polygone_keyboard) else self.xmin_input
		widget_input.setFocus()
		self.input_value(text, widget_input)

	def showorhide(self, widget):
		if widget.height() == 0:
			widget.setGeometry(QtCore.QRect(67, 220, 680, 227))
			widget.setMinimumSize(QtCore.QSize(680, 227))
			widget.setMaximumSize(QtCore.QSize(680, 227))
		else:
			widget.setMinimumSize(QtCore.QSize(0, 0))
			widget.setMaximumSize(QtCore.QSize(0, 0))
			widget.setGeometry(QtCore.QRect(0, 0, 0, 0))

	def input_value(self, v, input):
		input.setText(input.text()[:input.cursorPosition()] + v + input.text()[input.cursorPosition():]) 

	def keyboardf(self, parent, name):
		_translate = QtCore.QCoreApplication.translate
		name = QtWidgets.QGroupBox(parent)
		name.setGeometry(QtCore.QRect(0, 0, 0, 0))
		name.setStyleSheet("*{\n"
"    padding: 20px;\n"
"    background-color: #ccc;\n"
"}\n"
"QPushButton {\n"
"    padding: 0px;\n"
"    background-color: #fdfdfd;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 8px;\n"
"    font: 20px \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(240, 240, 240);\n"
"}")
		name.setTitle("")
		name.setObjectName("keyboard")
		self.numbers = QtWidgets.QGroupBox(name)
		self.numbers.setGeometry(QtCore.QRect(250, 2, 412, 220))
		self.numbers.setMinimumSize(QtCore.QSize(412, 220))
		self.numbers.setMaximumSize(QtCore.QSize(412, 220))
		self.numbers.setStyleSheet("border: none;")
		self.numbers.setTitle("")
		self.numbers.setObjectName("numbers")
		self.btn_7 = QtWidgets.QPushButton(self.numbers)
		self.btn_7.setGeometry(QtCore.QRect(0, 5, 100, 50))
		self.btn_7.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_7.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_7.setObjectName("btn_7")
		self.btn_7.setText(_translate("BresnhamMainWindow", "7"))
		self.btn_7.clicked.connect(lambda: self.toinput('7', name))
		self.btn_8 = QtWidgets.QPushButton(self.numbers)
		self.btn_8.setGeometry(QtCore.QRect(104, 5, 100, 50))
		self.btn_8.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_8.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_8.setObjectName("btn_8")
		self.btn_8.setText(_translate("BresnhamMainWindow", "8"))
		self.btn_8.clicked.connect(lambda: self.toinput('8', name))
		self.btn_9 = QtWidgets.QPushButton(self.numbers)
		self.btn_9.setGeometry(QtCore.QRect(208, 5, 100, 50))
		self.btn_9.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_9.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_9.setObjectName("btn_9")
		self.btn_9.setText(_translate("BresnhamMainWindow", "9"))
		self.btn_9.clicked.connect(lambda: self.toinput('9', name))
		self.divide_btn = QtWidgets.QPushButton(self.numbers)
		self.divide_btn.setGeometry(QtCore.QRect(312, 5, 100, 50))
		self.divide_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.divide_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.divide_btn.setObjectName("divide_btn")
		self.divide_btn.setText(_translate("BresnhamMainWindow", "/"))
		self.divide_btn.clicked.connect(lambda: self.toinput('/', name))
		self.btn_5 = QtWidgets.QPushButton(self.numbers)
		self.btn_5.setGeometry(QtCore.QRect(104, 60, 100, 50))
		self.btn_5.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_5.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_5.setObjectName("btn_5")
		self.btn_5.setText(_translate("BresnhamMainWindow", "5"))
		self.btn_5.clicked.connect(lambda: self.toinput('5', name))
		self.btn_4 = QtWidgets.QPushButton(self.numbers)
		self.btn_4.setGeometry(QtCore.QRect(0, 60, 100, 50))
		self.btn_4.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_4.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_4.setObjectName("btn_4")
		self.btn_4.setText(_translate("BresnhamMainWindow", "4"))
		self.btn_4.clicked.connect(lambda: self.toinput('4', name))
		self.btn_6 = QtWidgets.QPushButton(self.numbers)
		self.btn_6.setGeometry(QtCore.QRect(208, 60, 100, 50))
		self.btn_6.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_6.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_6.setObjectName("btn_6")
		self.btn_6.setText(_translate("BresnhamMainWindow", "6"))
		self.btn_6.clicked.connect(lambda: self.toinput('6', name))
		self.multiply_btn = QtWidgets.QPushButton(self.numbers)
		self.multiply_btn.setGeometry(QtCore.QRect(312, 60, 100, 50))
		self.multiply_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.multiply_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.multiply_btn.setObjectName("multiply_btn")
		self.multiply_btn.setText(_translate("BresnhamMainWindow", "x"))
		self.multiply_btn.clicked.connect(lambda: self.toinput('*', name))
		self.btn_2 = QtWidgets.QPushButton(self.numbers)
		self.btn_2.setGeometry(QtCore.QRect(104, 115, 100, 50))
		self.btn_2.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_2.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_2.setObjectName("btn_2")
		self.btn_2.setText(_translate("BresnhamMainWindow", "2"))
		self.btn_2.clicked.connect(lambda: self.toinput('2', name))
		self.btn_1 = QtWidgets.QPushButton(self.numbers)
		self.btn_1.setGeometry(QtCore.QRect(0, 115, 100, 50))
		self.btn_1.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_1.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_1.setObjectName("btn_1")
		self.btn_1.setText(_translate("BresnhamMainWindow", "1"))
		self.btn_1.clicked.connect(lambda: self.toinput('1', name))
		self.btn_3 = QtWidgets.QPushButton(self.numbers)
		self.btn_3.setGeometry(QtCore.QRect(208, 115, 100, 50))
		self.btn_3.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_3.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_3.setObjectName("btn_3")
		self.btn_3.setText(_translate("BresnhamMainWindow", "3"))
		self.btn_3.clicked.connect(lambda: self.toinput('3', name))
		self.minus_btn = QtWidgets.QPushButton(self.numbers)
		self.minus_btn.setGeometry(QtCore.QRect(312, 115, 100, 50))
		self.minus_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.minus_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.minus_btn.setObjectName("minus_btn")
		self.minus_btn.setText(_translate("BresnhamMainWindow", "-"))
		self.minus_btn.clicked.connect(lambda: self.toinput('-', name))
		self.btn_0 = QtWidgets.QPushButton(self.numbers)
		self.btn_0.setGeometry(QtCore.QRect(0, 170, 204, 50))
		self.btn_0.setMinimumSize(QtCore.QSize(204, 50))
		self.btn_0.setMaximumSize(QtCore.QSize(204, 50))
		self.btn_0.setObjectName("btn_0")
		self.btn_0.setText(_translate("BresnhamMainWindow", "0"))
		self.btn_0.clicked.connect(lambda: self.toinput('0', name))
		self.comma_btn = QtWidgets.QPushButton(self.numbers)
		self.comma_btn.setGeometry(QtCore.QRect(208, 170, 100, 50))
		self.comma_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.comma_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.comma_btn.setObjectName("comma_btn")
		self.comma_btn.setText(_translate("BresnhamMainWindow", "."))
		self.comma_btn.clicked.connect(lambda: self.toinput('.', name))
		self.plus_btn = QtWidgets.QPushButton(self.numbers)
		self.plus_btn.setGeometry(QtCore.QRect(312, 170, 100, 50))
		self.plus_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.plus_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.plus_btn.setObjectName("plus_btn")
		self.plus_btn.setText(_translate("BresnhamMainWindow", "+"))
		self.plus_btn.clicked.connect(lambda: self.toinput('+', name))
		self.characters = QtWidgets.QGroupBox(name)
		self.characters.setGeometry(QtCore.QRect(10, 2, 212, 220))
		self.characters.setMinimumSize(QtCore.QSize(212, 220))
		self.characters.setMaximumSize(QtCore.QSize(212, 220))
		self.characters.setStyleSheet("border: none;")
		self.characters.setTitle("")
		self.characters.setObjectName("characters")
		self.pi_btn = QtWidgets.QPushButton(self.characters)
		self.pi_btn.setGeometry(QtCore.QRect(0, 5, 104, 50))
		self.pi_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.pi_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.pi_btn.setObjectName("pi_btn")
		self.pi_btn.setText(_translate("BresnhamMainWindow", "π"))
		self.pi_btn.clicked.connect(lambda: self.toinput('π', name))
		self.square_btn = QtWidgets.QPushButton(self.characters)
		self.square_btn.setGeometry(QtCore.QRect(108, 5, 104, 50))
		self.square_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.square_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.square_btn.setObjectName("square_btn")
		self.square_btn.setText(_translate("BresnhamMainWindow", "a²"))
		self.square_btn.clicked.connect(lambda: self.toinput('^2', name))
		self.sqrt_btn = QtWidgets.QPushButton(self.characters)
		self.sqrt_btn.setGeometry(QtCore.QRect(0, 60, 104, 50))
		self.sqrt_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.sqrt_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.sqrt_btn.setObjectName("sqrt_btn")
		self.sqrt_btn.setText(_translate("BresnhamMainWindow", "√"))
		self.sqrt_btn.clicked.connect(lambda: self.toinput('sqrt(', name))
		self.power_btn = QtWidgets.QPushButton(self.characters)
		self.power_btn.setGeometry(QtCore.QRect(108, 60, 104, 50))
		self.power_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.power_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.power_btn.setObjectName("power_btn")
		self.power_btn.setText(_translate("BresnhamMainWindow", "aⁿ"))
		self.power_btn.clicked.connect(lambda: self.toinput('^', name))
		self.left_btn = QtWidgets.QPushButton(self.characters)
		self.left_btn.setGeometry(QtCore.QRect(0, 115, 104, 50))
		self.left_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.left_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.left_btn.setObjectName("left_btn")
		self.left_btn.setText(_translate("BresnhamMainWindow", "("))
		self.left_btn.clicked.connect(lambda: self.toinput('(', name))
		self.right_btn = QtWidgets.QPushButton(self.characters)
		self.right_btn.setGeometry(QtCore.QRect(108, 115, 104, 50))
		self.right_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.right_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.right_btn.setObjectName("right_btn")
		self.right_btn.clicked.connect(lambda: self.toinput(')', name))
		self.right_btn.setText(_translate("BresnhamMainWindow", ")"))
		self.exp_btn = QtWidgets.QPushButton(self.characters)
		self.exp_btn.setGeometry(QtCore.QRect(0, 170, 104, 50))
		self.exp_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.exp_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.exp_btn.setObjectName("exp_btn")
		self.exp_btn.setText(_translate("BresnhamMainWindow", "eⁿ"))
		self.exp_btn.clicked.connect(lambda: self.toinput('exp(', name))
		self.pof10_btn = QtWidgets.QPushButton(self.characters)
		self.pof10_btn.setGeometry(QtCore.QRect(108, 170, 104, 50))
		self.pof10_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.pof10_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.pof10_btn.setObjectName("pof10_btn")
		self.pof10_btn.setText(_translate("BresnhamMainWindow", "10ⁿ"))
		self.pof10_btn.clicked.connect(lambda: self.toinput('10^', name))
		return name


import resources


if __name__ == "__main__":
	import sys
	app = MyApplication(sys.argv)
	ClippingMainWindow = QtWidgets.QMainWindow()
	ui = Ui_ClippingMainWindow()
	ui.setupUi(ClippingMainWindow)
	ClippingMainWindow.show()
	sys.exit(app.exec_())
