#coding: utf_8

import matplotlib
matplotlib.use('Qt5Agg')
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, QEvent, pyqtSignal
from PyQt5.QtWidgets import (QWidget, QLineEdit, QLabel, QPushButton, QSizePolicy, QMessageBox, QFileDialog)
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas , NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
import numpy as np
from math import *
from sympy import *
from hermitg import Q
from bezier import Q_bezier , plot_line, generate_from_file
from bspline import S_abspline
from ibspline import s_ibspline

class PlotCanvas(FigureCanvas):
	def __init__(self, parent = None, width = 5, height = 4, dpi = 100):
		self.fig = Figure(figsize = (width, height), dpi= dpi)
		self.ax = self.fig.add_subplot(111)
		FigureCanvas.__init__(self, self.fig)
		self.setParent(parent)
		FigureCanvas.setSizePolicy(self, QSizePolicy.Expanding, QSizePolicy.Expanding)
		FigureCanvas.updateGeometry(self)

	def plot_hermit(self, data):
		self.ax.remove()
		self.ax = self.fig.add_subplot(111)
		self.ax.cla()
		self.ax.set_title('Hermit Curve')
		t = symbols('t')
		qf = Q(*data)
		xm = max(abs(data[0]), abs(data[1])) + 3
		x = np.linspace(-xm, xm, 1000)
		y = lambdify(t, qf)(x)
		self.ax.plot(x, np.transpose(y), 'r')
		self.ax.scatter(data[0], data[2])
		self.ax.scatter(data[1], data[3])
		self.ax.annotate(f'{data[0], data[2]}', (data[0], data[2]))
		self.ax.annotate(f'{data[1], data[3]}', (data[1], data[3]))
		ym = max(abs(data[2]), abs(data[3])) + 5
		self.ax.set_ylim([-ym , ym])
		self.ax.spines['left'].set_position('zero')
		self.ax.spines['right'].set_color('none')
		self.ax.yaxis.tick_left()
		self.ax.spines['bottom'].set_position('zero')
		self.ax.spines['top'].set_color('none')
		self.ax.xaxis.tick_bottom()
		self.draw()

	def plot_bezier(self, p):
		t = symbols('t')
		qf = Q_bezier(p)
		n = len(p)
		d = len(p[0])
		if d == 2:
			self.ax.remove()
			self.ax = self.fig.add_subplot(111)
			self.ax.cla()
			self.ax.set_title('Bézier Curve')
			for i in range(n -1):
				k = (i+1)
				plot_line(self.ax, p[i], p[k], 'r')
			ymin = min(p, key = lambda tup : tup[1])[1]
			ymax = max(p, key = lambda tup : tup[1])[1]
			xmin = min(p, key = lambda tup : tup[0])[0]
			xmax = max(p, key = lambda tup : tup[0])[0]
			tt = np.linspace(0, 1, 1000)
			x = lambdify(t, qf[0])(tt)
			y = lambdify(t, qf[1])(tt)
			self.ax.plot(x, y)
			self.ax.set_ylim([ymin - 1, ymax + 1])
			self.ax.set_xlim([xmin - 1, xmax + 1])
			self.ax.spines['left'].set_position('zero')
			self.ax.spines['right'].set_color('none')
			self.ax.yaxis.tick_left()
			self.ax.spines['bottom'].set_position('zero')
			self.ax.spines['top'].set_color('none')
			self.ax.xaxis.tick_bottom()
		else:
			self.ax.remove()
			self.ax = self.fig.add_subplot(111, projection='3d')
			self.ax.cla()
			self.ax.set_title('Bézier Curve')
			tt = np.linspace(0, 1, 1000)
			X = lambdify(t, qf[0])(tt)
			Y = lambdify(t, qf[1])(tt)
			Z = lambdify(t, qf[2])(tt)
			if not type(Z).__module__ == np.__name__:
				Z = np.array([0] * 1000)
			x = np.reshape(X, (25, 40))
			y = np.reshape(Y, (25, 40))
			z = np.reshape(Z, (25, 40))
			self.ax.plot_wireframe(x,y,z)
		self.draw()

	def plot_ibspline(self, p, boundry_condition, c1, c2):
		self.ax.remove()
		self.ax = self.fig.add_subplot(111)
		self.ax.cla()
		self.ax.set_title('B-spline Interpolation Curve')
		n = len(p)
		for i in range(n -1):
			k = (i+1)
			plot_line(self.ax, p[i], p[k], 'r')
		ymin = min(p, key = lambda tup : tup[1])[1]
		ymax = max(p, key = lambda tup : tup[1])[1]
		xmin = min(p, key = lambda tup : tup[0])[0]
		xmax = max(p, key = lambda tup : tup[0])[0]
		x = np.linspace(xmin, xmax, 1000)
		y = [s_ibspline(t, p, boundry_condition, c1, c2) for t in x]
		self.ax.plot(x, y)
		self.ax.spines['left'].set_position('zero')
		self.ax.spines['right'].set_color('none')
		self.ax.yaxis.tick_left()
		self.ax.spines['bottom'].set_position('zero')
		self.ax.spines['top'].set_color('none')
		self.ax.xaxis.tick_bottom()
		self.draw()

	def plot_abspline(self, p):
		n = len(p)
		d = len(p[0])
		if d == 2:
			self.ax.remove()
			self.ax = self.fig.add_subplot(111)
			self.ax.set_title('B-Spline Approximation Curve')
			for i in range(n -1):
				k = (i+1)
				plot_line(self.ax, p[i], p[k], 'r')
			t = np.linspace(0, 1, 1000, endpoint = False)
			x = [S_abspline(p, 2, k)[0] for k in t]
			y = [S_abspline(p, 2, k)[1] for k in t]
			self.ax.plot(x, y, 'b')
			self.ax.spines['left'].set_position('zero')
			self.ax.spines['right'].set_color('none')
			self.ax.yaxis.tick_left()
			self.ax.spines['bottom'].set_position('zero')
			self.ax.spines['top'].set_color('none')
			self.ax.xaxis.tick_bottom()
		else:
			self.ax.remove()
			self.ax = self.fig.add_subplot(111, projection='3d')
			self.ax.set_title('B-Spline Approximation Curve')
			t = np.linspace(0, 1, 1000, endpoint = False)
			result = np.array([S_abspline(p, 2, k) for k in t])
			X = [r[0] for r in result]
			Y = [r[1] for r in result]
			Z = [r[2] for r in result]
			if not type(Z).__module__ == np.__name__:
				Z = np.array([0] * 1000)
			x = np.reshape(X, (25, 40))
			y = np.reshape(Y, (25, 40))
			z = np.reshape(Z, (25, 40))
			self.ax.plot_wireframe(x,y,z)
		self.draw()
	
class inputFocusFilter(QObject):
	focusIn = pyqtSignal(object)
	def eventFilter(self, widget, event):
		if event.type() == QEvent.FocusIn and isinstance(widget, QLineEdit):
			self.focusIn.emit(widget)
		return super(inputFocusFilter, self).eventFilter(widget, event)


class MyApplication(QtWidgets.QApplication):
	def __init__(self, *arg, **kwarg):
		super(MyApplication, self).__init__(*arg, **kwarg)

		self._input_focus_widget = None

		self.event_filter = inputFocusFilter()
		self.event_filter.focusIn.connect(self.setInputFocusWidget)
		self.installEventFilter(self.event_filter)

	def setInputFocusWidget(self, widget):
		self._input_focus_widget = widget

	def inputFocusWidget(self):
		return self._input_focus_widget



class Ui_CurvesMainWindow(object):
	def __init__(self):
		self.new = False
	def setupUi(self, CurvesMainWindow):
		CurvesMainWindow.setObjectName("CurvesMainWindow")
		CurvesMainWindow.resize(1024, 768)
		CurvesMainWindow.setMinimumSize(QtCore.QSize(1024, 768))
		CurvesMainWindow.setMaximumSize(QtCore.QSize(1024, 768))
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("cg.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		CurvesMainWindow.setWindowIcon(icon)
		self.centralwidget = QtWidgets.QWidget(CurvesMainWindow)
		self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.centralwidget.setObjectName("centralwidget")
		self.bresnham_menu = QtWidgets.QGroupBox(self.centralwidget)
		self.bresnham_menu.setGeometry(QtCore.QRect(0, 0, 200, 768))
		self.bresnham_menu.setMinimumSize(QtCore.QSize(200, 768))
		self.bresnham_menu.setMaximumSize(QtCore.QSize(200, 768))
		self.bresnham_menu.setStyleSheet("*{\n"
"    background-color: #87ffcd;\n"
"    margin: 0;\n"
"    width: 100%;\n"
"    height: 100%\n"
"}\n"
"QPushButton {\n"
"    min-width: 100%;\n"
"    margin: 0;\n"
"    padding: 10px;\n"
"    font: 75 16px \"MS Shell Dlg 2\";\n"
"    height: auto;\n"
"    outline: None; \n"
"    border: None\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5c49d6;\n"
"    color: #fff\n"
"}")
		self.bresnham_menu.setTitle("")
		self.bresnham_menu.setObjectName("bresnham_menu")
		self.select_hermit = QtWidgets.QPushButton(self.bresnham_menu)
		self.select_hermit.setGeometry(QtCore.QRect(0, 15, 200, 60))
		self.select_hermit.setMinimumSize(QtCore.QSize(120, 60))
		self.select_hermit.setMaximumSize(QtCore.QSize(200, 60))
		self.select_hermit.setStyleSheet("")
		self.select_hermit.setObjectName("select_hermit")
		self.select_bezier = QtWidgets.QPushButton(self.bresnham_menu)
		self.select_bezier.setGeometry(QtCore.QRect(0, 75, 200, 60))
		self.select_bezier.setMinimumSize(QtCore.QSize(120, 60))
		self.select_bezier.setMaximumSize(QtCore.QSize(200, 60))
		self.select_bezier.setStyleSheet("")
		self.select_bezier.setObjectName("select_bezier")
		self.select_interb = QtWidgets.QPushButton(self.bresnham_menu)
		self.select_interb.setGeometry(QtCore.QRect(0, 135, 200, 60))
		self.select_interb.setMinimumSize(QtCore.QSize(120, 60))
		self.select_interb.setMaximumSize(QtCore.QSize(200, 60))
		self.select_interb.setStyleSheet("")
		self.select_interb.setObjectName("select_interb")
		self.select_quit = QtWidgets.QPushButton(self.bresnham_menu)
		self.select_quit.setGeometry(QtCore.QRect(0, 600, 200, 60))
		self.select_quit.setMinimumSize(QtCore.QSize(120, 60))
		self.select_quit.setMaximumSize(QtCore.QSize(200, 60))
		self.select_quit.setStyleSheet("")
		self.select_quit.setObjectName("select_quit")
		self.select_approxb = QtWidgets.QPushButton(self.bresnham_menu)
		self.select_approxb.setGeometry(QtCore.QRect(0, 195, 200, 60))
		self.select_approxb.setMinimumSize(QtCore.QSize(120, 60))
		self.select_approxb.setMaximumSize(QtCore.QSize(200, 60))
		self.select_approxb.setStyleSheet("")
		self.select_approxb.setObjectName("select_approxb")
		self.curves_stacked = QtWidgets.QStackedWidget(self.centralwidget)
		self.curves_stacked.setGeometry(QtCore.QRect(200, 0, 820, 768))
		self.curves_stacked.setMinimumSize(QtCore.QSize(820, 768))
		self.curves_stacked.setMaximumSize(QtCore.QSize(820, 750))
		self.curves_stacked.setObjectName("curves_stacked")
		self.bezier = QtWidgets.QWidget()
		self.bezier.setObjectName("bezier")
		#bezier plotting
		self.bezier_graph_box = QtWidgets.QGroupBox(self.bezier)
		self.bezier_graph_box.setGeometry(QtCore.QRect(60, 220, 691, 511))
		bezier_graph = PlotCanvas(self.bezier_graph_box, width=6.9, height=5.1, dpi=100)
		bezier_toolbar = NavigationToolbar(bezier_graph, self.bezier_graph_box)
		bezier_toolbar.move(80, 0)		
		self.bezier_graph_box.setStyleSheet("border: none;\n")
		self.bezier_ok = QtWidgets.QPushButton(self.bezier)
		self.bezier_ok.setGeometry(QtCore.QRect(580, 114, 100, 40))
		self.bezier_ok.clicked.connect(lambda: self.bezier_graph_plot(bezier_graph))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.bezier_ok.setFont(font)
		self.bezier_ok.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.bezier_ok.setObjectName("bezier_ok")
		self.bezier_keyboard_btn = QtWidgets.QPushButton(self.bezier)
		self.bezier_keyboard_btn.setGeometry(QtCore.QRect(580, 162, 100, 40))
		self.bezier_keyboard_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.bezier_keyboard_btn.setText("")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/newPrefix/keyboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		self.bezier_keyboard_btn.setIcon(icon)
		self.bezier_keyboard_btn.setIconSize(QtCore.QSize(100, 50))
		self.bezier_keyboard_btn.setObjectName("bezier_keyboard_btn")
		self.bezier_keyboard = None
		self.bezier_keyboard = self.keyboardf(self.bezier, self.bezier_keyboard, (67, 220, 680, 227))
		self.bezier_keyboard_btn.clicked.connect(lambda: self.showorhide(self.bezier_keyboard, (67, 220, 680, 227)))
		self.bezier_upload_btn = QtWidgets.QPushButton(self.bezier)
		self.bezier_upload_btn.setGeometry(QtCore.QRect(580, 68, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.bezier_upload_btn.setFont(font)
		self.bezier_upload_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/newPrefix/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		self.bezier_upload_btn.setIcon(icon1)
		self.bezier_upload_btn.setIconSize(QtCore.QSize(24, 24))
		self.bezier_upload_btn.setObjectName("bezier_upload_btn")
		self.bezier_new_btn = QtWidgets.QPushButton(self.bezier)
		self.bezier_new_btn.setGeometry(QtCore.QRect(580, 20, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.bezier_new_btn.setFont(font)
		self.bezier_new_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.bezier_new_btn.setObjectName("bezier_new_btn")
		self.groupBox_5 = QtWidgets.QGroupBox(self.bezier)
		self.groupBox_5.setGeometry(QtCore.QRect(110, 10, 451, 200))
		self.groupBox_5.setMinimumSize(QtCore.QSize(250, 200))
		self.groupBox_5.setMaximumSize(QtCore.QSize(520, 200))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(11)
		self.groupBox_5.setFont(font)
		self.groupBox_5.setStyleSheet("background-color: #abff8d;")
		self.groupBox_5.setObjectName("groupBox_5")
		self.bezier_p1 = QtWidgets.QLineEdit(self.groupBox_5)
		self.bezier_p1.setGeometry(QtCore.QRect(70, 35, 65, 24))
		self.bezier_p1.setMinimumSize(QtCore.QSize(65, 0))
		self.bezier_p1.setMaximumSize(QtCore.QSize(40, 24))
		self.bezier_p1.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.bezier_p1.setText("")
		self.bezier_p1.setObjectName("bezier_p1")
		self.label_73 = QtWidgets.QLabel(self.groupBox_5)
		self.label_73.setGeometry(QtCore.QRect(40, 30, 22, 30))
		self.label_73.setMinimumSize(QtCore.QSize(22, 30))
		self.label_73.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_73.setFont(font)
		self.label_73.setObjectName("label_73")
		self.label_74 = QtWidgets.QLabel(self.groupBox_5)
		self.label_74.setGeometry(QtCore.QRect(140, 30, 10, 30))
		self.label_74.setMinimumSize(QtCore.QSize(10, 30))
		self.label_74.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_74.setFont(font)
		self.label_74.setObjectName("label_74")
		self.bezier_p2 = QtWidgets.QLineEdit(self.groupBox_5)
		self.bezier_p2.setGeometry(QtCore.QRect(205, 35, 65, 24))
		self.bezier_p2.setMinimumSize(QtCore.QSize(65, 0))
		self.bezier_p2.setMaximumSize(QtCore.QSize(40, 24))
		self.bezier_p2.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.bezier_p2.setText("")
		self.bezier_p2.setObjectName("bezier_p2")
		self.label_75 = QtWidgets.QLabel(self.groupBox_5)
		self.label_75.setGeometry(QtCore.QRect(275, 30, 10, 30))
		self.label_75.setMinimumSize(QtCore.QSize(10, 30))
		self.label_75.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_75.setFont(font)
		self.label_75.setObjectName("label_75")
		self.label_76 = QtWidgets.QLabel(self.groupBox_5)
		self.label_76.setGeometry(QtCore.QRect(180, 30, 22, 30))
		self.label_76.setMinimumSize(QtCore.QSize(22, 30))
		self.label_76.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_76.setFont(font)
		self.label_76.setObjectName("label_76")
		self.bezier_p3 = QtWidgets.QLineEdit(self.groupBox_5)
		self.bezier_p3.setGeometry(QtCore.QRect(335, 35, 65, 24))
		self.bezier_p3.setMinimumSize(QtCore.QSize(65, 0))
		self.bezier_p3.setMaximumSize(QtCore.QSize(40, 24))
		self.bezier_p3.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.bezier_p3.setText("")
		self.bezier_p3.setObjectName("bezier_p3")
		self.label_77 = QtWidgets.QLabel(self.groupBox_5)
		self.label_77.setGeometry(QtCore.QRect(405, 30, 10, 30))
		self.label_77.setMinimumSize(QtCore.QSize(10, 30))
		self.label_77.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_77.setFont(font)
		self.label_77.setObjectName("label_77")
		self.label_78 = QtWidgets.QLabel(self.groupBox_5)
		self.label_78.setGeometry(QtCore.QRect(305, 30, 22, 30))
		self.label_78.setMinimumSize(QtCore.QSize(22, 30))
		self.label_78.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_78.setFont(font)
		self.label_78.setObjectName("label_78")
		self.label_79 = QtWidgets.QLabel(self.groupBox_5)
		self.label_79.setGeometry(QtCore.QRect(405, 80, 10, 30))
		self.label_79.setMinimumSize(QtCore.QSize(10, 30))
		self.label_79.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_79.setFont(font)
		self.label_79.setObjectName("label_79")
		self.label_80 = QtWidgets.QLabel(self.groupBox_5)
		self.label_80.setGeometry(QtCore.QRect(305, 80, 22, 30))
		self.label_80.setMinimumSize(QtCore.QSize(22, 30))
		self.label_80.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_80.setFont(font)
		self.label_80.setObjectName("label_80")
		self.label_81 = QtWidgets.QLabel(self.groupBox_5)
		self.label_81.setGeometry(QtCore.QRect(140, 80, 10, 30))
		self.label_81.setMinimumSize(QtCore.QSize(10, 30))
		self.label_81.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_81.setFont(font)
		self.label_81.setObjectName("label_81")
		self.bezier_p5 = QtWidgets.QLineEdit(self.groupBox_5)
		self.bezier_p5.setGeometry(QtCore.QRect(205, 85, 65, 24))
		self.bezier_p5.setMinimumSize(QtCore.QSize(65, 0))
		self.bezier_p5.setMaximumSize(QtCore.QSize(40, 24))
		self.bezier_p5.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.bezier_p5.setText("")
		self.bezier_p5.setObjectName("bezier_p5")
		self.label_82 = QtWidgets.QLabel(self.groupBox_5)
		self.label_82.setGeometry(QtCore.QRect(40, 80, 22, 30))
		self.label_82.setMinimumSize(QtCore.QSize(22, 30))
		self.label_82.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_82.setFont(font)
		self.label_82.setObjectName("label_82")
		self.label_83 = QtWidgets.QLabel(self.groupBox_5)
		self.label_83.setGeometry(QtCore.QRect(275, 80, 10, 30))
		self.label_83.setMinimumSize(QtCore.QSize(10, 30))
		self.label_83.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_83.setFont(font)
		self.label_83.setObjectName("label_83")
		self.bezier_p6 = QtWidgets.QLineEdit(self.groupBox_5)
		self.bezier_p6.setGeometry(QtCore.QRect(335, 85, 65, 24))
		self.bezier_p6.setMinimumSize(QtCore.QSize(65, 0))
		self.bezier_p6.setMaximumSize(QtCore.QSize(40, 24))
		self.bezier_p6.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.bezier_p6.setText("")
		self.bezier_p6.setObjectName("bezier_p6")
		self.bezier_p4 = QtWidgets.QLineEdit(self.groupBox_5)
		self.bezier_p4.setGeometry(QtCore.QRect(70, 85, 65, 24))
		self.bezier_p4.setMinimumSize(QtCore.QSize(65, 0))
		self.bezier_p4.setMaximumSize(QtCore.QSize(40, 24))
		self.bezier_p4.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.bezier_p4.setText("")
		self.bezier_p4.setObjectName("bezier_p4")
		self.label_84 = QtWidgets.QLabel(self.groupBox_5)
		self.label_84.setGeometry(QtCore.QRect(180, 80, 22, 30))
		self.label_84.setMinimumSize(QtCore.QSize(22, 30))
		self.label_84.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_84.setFont(font)
		self.label_84.setObjectName("label_84")
		self.label_85 = QtWidgets.QLabel(self.groupBox_5)
		self.label_85.setGeometry(QtCore.QRect(405, 130, 10, 30))
		self.label_85.setMinimumSize(QtCore.QSize(10, 30))
		self.label_85.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_85.setFont(font)
		self.label_85.setObjectName("label_85")
		self.label_86 = QtWidgets.QLabel(self.groupBox_5)
		self.label_86.setGeometry(QtCore.QRect(305, 130, 22, 30))
		self.label_86.setMinimumSize(QtCore.QSize(22, 30))
		self.label_86.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_86.setFont(font)
		self.label_86.setObjectName("label_86")
		self.label_87 = QtWidgets.QLabel(self.groupBox_5)
		self.label_87.setGeometry(QtCore.QRect(140, 130, 10, 30))
		self.label_87.setMinimumSize(QtCore.QSize(10, 30))
		self.label_87.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_87.setFont(font)
		self.label_87.setObjectName("label_87")
		self.bezier_p8 = QtWidgets.QLineEdit(self.groupBox_5)
		self.bezier_p8.setGeometry(QtCore.QRect(205, 135, 65, 24))
		self.bezier_p8.setMinimumSize(QtCore.QSize(65, 0))
		self.bezier_p8.setMaximumSize(QtCore.QSize(40, 24))
		self.bezier_p8.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.bezier_p8.setText("")
		self.bezier_p8.setObjectName("bezier_p8")
		self.label_88 = QtWidgets.QLabel(self.groupBox_5)
		self.label_88.setGeometry(QtCore.QRect(40, 130, 22, 30))
		self.label_88.setMinimumSize(QtCore.QSize(22, 30))
		self.label_88.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_88.setFont(font)
		self.label_88.setObjectName("label_88")
		self.label_89 = QtWidgets.QLabel(self.groupBox_5)
		self.label_89.setGeometry(QtCore.QRect(275, 130, 10, 30))
		self.label_89.setMinimumSize(QtCore.QSize(10, 30))
		self.label_89.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_89.setFont(font)
		self.label_89.setObjectName("label_89")
		self.bezier_p9 = QtWidgets.QLineEdit(self.groupBox_5)
		self.bezier_p9.setGeometry(QtCore.QRect(335, 135, 65, 24))
		self.bezier_p9.setMinimumSize(QtCore.QSize(65, 0))
		self.bezier_p9.setMaximumSize(QtCore.QSize(40, 24))
		self.bezier_p9.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.bezier_p9.setText("")
		self.bezier_p9.setObjectName("bezier_p9")
		self.bezier_p7 = QtWidgets.QLineEdit(self.groupBox_5)
		self.bezier_p7.setGeometry(QtCore.QRect(70, 135, 65, 24))
		self.bezier_p7.setMinimumSize(QtCore.QSize(65, 0))
		self.bezier_p7.setMaximumSize(QtCore.QSize(40, 24))
		self.bezier_p7.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.bezier_p7.setText("")
		self.bezier_p7.setObjectName("bezier_p7")
		self.label_90 = QtWidgets.QLabel(self.groupBox_5)
		self.label_90.setGeometry(QtCore.QRect(180, 130, 22, 30))
		self.label_90.setMinimumSize(QtCore.QSize(22, 30))
		self.label_90.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_90.setFont(font)
		self.label_90.setObjectName("label_90")
		self.bezier_upload_btn.clicked.connect(lambda : self.bezier_from_upload(bezier_graph, CurvesMainWindow))
		self.curves_stacked.addWidget(self.bezier)
		self.abspline = QtWidgets.QWidget()
		self.abspline.setObjectName("abspline")
		self.abspline_ok = QtWidgets.QPushButton(self.abspline)
		self.abspline_ok.setGeometry(QtCore.QRect(580, 116, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.abspline_ok.setFont(font)
		self.abspline_ok.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.abspline_ok.setObjectName("abspline_ok")
		self.abspline_upload_btn = QtWidgets.QPushButton(self.abspline)
		self.abspline_upload_btn.setGeometry(QtCore.QRect(580, 69, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.abspline_upload_btn.setFont(font)
		self.abspline_upload_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.abspline_upload_btn.setIcon(icon1)
		self.abspline_upload_btn.setIconSize(QtCore.QSize(24, 24))
		self.abspline_upload_btn.setObjectName("abspline_upload_btn")
		self.abspline_keyboard_btn = QtWidgets.QPushButton(self.abspline)
		self.abspline_keyboard_btn.setGeometry(QtCore.QRect(580, 168, 100, 40))
		self.abspline_keyboard_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.abspline_keyboard_btn.setText("")
		self.abspline_keyboard_btn.setIcon(icon)
		self.abspline_keyboard_btn.setIconSize(QtCore.QSize(100, 50))
		self.abspline_keyboard_btn.setObjectName("abspline_keyboard_btn")
		#abspline plotting
		self.abspline_graph_box = QtWidgets.QGroupBox(self.abspline)
		self.abspline_graph_box.setGeometry(QtCore.QRect(60, 220, 691, 511))
		abspline_graph = PlotCanvas(self.abspline_graph_box, width=6.9, height=5.1, dpi=100)
		abspline_toolbar = NavigationToolbar(abspline_graph, self.abspline_graph_box)
		abspline_toolbar.move(80, 0)		
		self.abspline_graph_box.setStyleSheet("border: none;\n")
		self.abspline_ok.clicked.connect(lambda: self.abspline_graph_plot(abspline_graph))
		self.abspline_new_btn = QtWidgets.QPushButton(self.abspline)
		self.abspline_new_btn.setGeometry(QtCore.QRect(580, 20, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.abspline_new_btn.setFont(font)
		self.abspline_new_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.abspline_new_btn.setObjectName("abspline_new_btn")
		self.abspline_keyboard = None
		self.abspline_keyboard = self.keyboardf(self.abspline, self.abspline_keyboard, (67, 220, 680, 227))
		self.abspline_keyboard_btn.clicked.connect(lambda: self.showorhide(self.abspline_keyboard, (67, 220, 680, 227)))
		self.groupBox_6 = QtWidgets.QGroupBox(self.abspline)
		self.groupBox_6.setGeometry(QtCore.QRect(120, 10, 451, 200))
		self.groupBox_6.setMinimumSize(QtCore.QSize(250, 200))
		self.groupBox_6.setMaximumSize(QtCore.QSize(520, 200))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(11)
		self.groupBox_6.setFont(font)
		self.groupBox_6.setStyleSheet("background-color: #abff8d;")
		self.groupBox_6.setObjectName("groupBox_6")
		self.abspline_p1 = QtWidgets.QLineEdit(self.groupBox_6)
		self.abspline_p1.setGeometry(QtCore.QRect(70, 35, 65, 24))
		self.abspline_p1.setMinimumSize(QtCore.QSize(65, 0))
		self.abspline_p1.setMaximumSize(QtCore.QSize(40, 24))
		self.abspline_p1.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.abspline_p1.setText("")
		self.abspline_p1.setObjectName("abspline_p1")
		self.label_91 = QtWidgets.QLabel(self.groupBox_6)
		self.label_91.setGeometry(QtCore.QRect(40, 30, 22, 30))
		self.label_91.setMinimumSize(QtCore.QSize(22, 30))
		self.label_91.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_91.setFont(font)
		self.label_91.setObjectName("label_91")
		self.label_92 = QtWidgets.QLabel(self.groupBox_6)
		self.label_92.setGeometry(QtCore.QRect(140, 30, 10, 30))
		self.label_92.setMinimumSize(QtCore.QSize(10, 30))
		self.label_92.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_92.setFont(font)
		self.label_92.setObjectName("label_92")
		self.abspline_p2 = QtWidgets.QLineEdit(self.groupBox_6)
		self.abspline_p2.setGeometry(QtCore.QRect(205, 35, 65, 24))
		self.abspline_p2.setMinimumSize(QtCore.QSize(65, 0))
		self.abspline_p2.setMaximumSize(QtCore.QSize(40, 24))
		self.abspline_p2.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.abspline_p2.setText("")
		self.abspline_p2.setObjectName("abspline_p2")
		self.label_93 = QtWidgets.QLabel(self.groupBox_6)
		self.label_93.setGeometry(QtCore.QRect(275, 30, 10, 30))
		self.label_93.setMinimumSize(QtCore.QSize(10, 30))
		self.label_93.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_93.setFont(font)
		self.label_93.setObjectName("label_93")
		self.label_94 = QtWidgets.QLabel(self.groupBox_6)
		self.label_94.setGeometry(QtCore.QRect(180, 30, 22, 30))
		self.label_94.setMinimumSize(QtCore.QSize(22, 30))
		self.label_94.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_94.setFont(font)
		self.label_94.setObjectName("label_94")
		self.abspline_p3 = QtWidgets.QLineEdit(self.groupBox_6)
		self.abspline_p3.setGeometry(QtCore.QRect(335, 35, 65, 24))
		self.abspline_p3.setMinimumSize(QtCore.QSize(65, 0))
		self.abspline_p3.setMaximumSize(QtCore.QSize(40, 24))
		self.abspline_p3.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.abspline_p3.setText("")
		self.abspline_p3.setObjectName("abspline_p3")
		self.label_95 = QtWidgets.QLabel(self.groupBox_6)
		self.label_95.setGeometry(QtCore.QRect(405, 30, 10, 30))
		self.label_95.setMinimumSize(QtCore.QSize(10, 30))
		self.label_95.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_95.setFont(font)
		self.label_95.setObjectName("label_95")
		self.label_96 = QtWidgets.QLabel(self.groupBox_6)
		self.label_96.setGeometry(QtCore.QRect(305, 30, 22, 30))
		self.label_96.setMinimumSize(QtCore.QSize(22, 30))
		self.label_96.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_96.setFont(font)
		self.label_96.setObjectName("label_96")
		self.label_97 = QtWidgets.QLabel(self.groupBox_6)
		self.label_97.setGeometry(QtCore.QRect(405, 80, 10, 30))
		self.label_97.setMinimumSize(QtCore.QSize(10, 30))
		self.label_97.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_97.setFont(font)
		self.label_97.setObjectName("label_97")
		self.label_98 = QtWidgets.QLabel(self.groupBox_6)
		self.label_98.setGeometry(QtCore.QRect(305, 80, 22, 30))
		self.label_98.setMinimumSize(QtCore.QSize(22, 30))
		self.label_98.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_98.setFont(font)
		self.label_98.setObjectName("label_98")
		self.label_99 = QtWidgets.QLabel(self.groupBox_6)
		self.label_99.setGeometry(QtCore.QRect(140, 80, 10, 30))
		self.label_99.setMinimumSize(QtCore.QSize(10, 30))
		self.label_99.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_99.setFont(font)
		self.label_99.setObjectName("label_99")
		self.abspline_p5 = QtWidgets.QLineEdit(self.groupBox_6)
		self.abspline_p5.setGeometry(QtCore.QRect(205, 85, 65, 24))
		self.abspline_p5.setMinimumSize(QtCore.QSize(65, 0))
		self.abspline_p5.setMaximumSize(QtCore.QSize(40, 24))
		self.abspline_p5.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.abspline_p5.setText("")
		self.abspline_p5.setObjectName("abspline_p5")
		self.label_100 = QtWidgets.QLabel(self.groupBox_6)
		self.label_100.setGeometry(QtCore.QRect(40, 80, 22, 30))
		self.label_100.setMinimumSize(QtCore.QSize(22, 30))
		self.label_100.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_100.setFont(font)
		self.label_100.setObjectName("label_100")
		self.label_101 = QtWidgets.QLabel(self.groupBox_6)
		self.label_101.setGeometry(QtCore.QRect(275, 80, 10, 30))
		self.label_101.setMinimumSize(QtCore.QSize(10, 30))
		self.label_101.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_101.setFont(font)
		self.label_101.setObjectName("label_101")
		self.abspline_p6 = QtWidgets.QLineEdit(self.groupBox_6)
		self.abspline_p6.setGeometry(QtCore.QRect(335, 85, 65, 24))
		self.abspline_p6.setMinimumSize(QtCore.QSize(65, 0))
		self.abspline_p6.setMaximumSize(QtCore.QSize(40, 24))
		self.abspline_p6.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.abspline_p6.setText("")
		self.abspline_p6.setObjectName("abspline_p6")
		self.abspline_p4 = QtWidgets.QLineEdit(self.groupBox_6)
		self.abspline_p4.setGeometry(QtCore.QRect(70, 85, 65, 24))
		self.abspline_p4.setMinimumSize(QtCore.QSize(65, 0))
		self.abspline_p4.setMaximumSize(QtCore.QSize(40, 24))
		self.abspline_p4.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.abspline_p4.setText("")
		self.abspline_p4.setObjectName("abspline_p4")
		self.label_102 = QtWidgets.QLabel(self.groupBox_6)
		self.label_102.setGeometry(QtCore.QRect(180, 80, 22, 30))
		self.label_102.setMinimumSize(QtCore.QSize(22, 30))
		self.label_102.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_102.setFont(font)
		self.label_102.setObjectName("label_102")
		self.label_103 = QtWidgets.QLabel(self.groupBox_6)
		self.label_103.setGeometry(QtCore.QRect(405, 130, 10, 30))
		self.label_103.setMinimumSize(QtCore.QSize(10, 30))
		self.label_103.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_103.setFont(font)
		self.label_103.setObjectName("label_103")
		self.label_104 = QtWidgets.QLabel(self.groupBox_6)
		self.label_104.setGeometry(QtCore.QRect(305, 130, 22, 30))
		self.label_104.setMinimumSize(QtCore.QSize(22, 30))
		self.label_104.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_104.setFont(font)
		self.label_104.setObjectName("label_104")
		self.label_105 = QtWidgets.QLabel(self.groupBox_6)
		self.label_105.setGeometry(QtCore.QRect(140, 130, 10, 30))
		self.label_105.setMinimumSize(QtCore.QSize(10, 30))
		self.label_105.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_105.setFont(font)
		self.label_105.setObjectName("label_105")
		self.abspline_p8 = QtWidgets.QLineEdit(self.groupBox_6)
		self.abspline_p8.setGeometry(QtCore.QRect(205, 135, 65, 24))
		self.abspline_p8.setMinimumSize(QtCore.QSize(65, 0))
		self.abspline_p8.setMaximumSize(QtCore.QSize(40, 24))
		self.abspline_p8.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.abspline_p8.setText("")
		self.abspline_p8.setObjectName("abspline_p8")
		self.label_106 = QtWidgets.QLabel(self.groupBox_6)
		self.label_106.setGeometry(QtCore.QRect(40, 130, 22, 30))
		self.label_106.setMinimumSize(QtCore.QSize(22, 30))
		self.label_106.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_106.setFont(font)
		self.label_106.setObjectName("label_106")
		self.label_107 = QtWidgets.QLabel(self.groupBox_6)
		self.label_107.setGeometry(QtCore.QRect(275, 130, 10, 30))
		self.label_107.setMinimumSize(QtCore.QSize(10, 30))
		self.label_107.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_107.setFont(font)
		self.label_107.setObjectName("label_107")
		self.abspline_p9 = QtWidgets.QLineEdit(self.groupBox_6)
		self.abspline_p9.setGeometry(QtCore.QRect(335, 135, 65, 24))
		self.abspline_p9.setMinimumSize(QtCore.QSize(65, 0))
		self.abspline_p9.setMaximumSize(QtCore.QSize(40, 24))
		self.abspline_p9.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.abspline_p9.setText("")
		self.abspline_p9.setObjectName("abspline_p9")
		self.abspline_p7 = QtWidgets.QLineEdit(self.groupBox_6)
		self.abspline_p7.setGeometry(QtCore.QRect(70, 135, 65, 24))
		self.abspline_p7.setMinimumSize(QtCore.QSize(65, 0))
		self.abspline_p7.setMaximumSize(QtCore.QSize(40, 24))
		self.abspline_p7.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.abspline_p7.setText("")
		self.abspline_p7.setObjectName("abspline_p7")
		self.label_108 = QtWidgets.QLabel(self.groupBox_6)
		self.label_108.setGeometry(QtCore.QRect(180, 130, 22, 30))
		self.label_108.setMinimumSize(QtCore.QSize(22, 30))
		self.label_108.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_108.setFont(font)
		self.label_108.setObjectName("label_108")
		self.abspline_upload_btn.clicked.connect(lambda : self.abspline_from_upload(abspline_graph, CurvesMainWindow))
		self.curves_stacked.addWidget(self.abspline)
		self.hermit = QtWidgets.QWidget()
		self.hermit.setObjectName("hermit")
		#plot hermit
		self.hermit_graph_box = QtWidgets.QGroupBox(self.hermit)
		self.hermit_graph_box.setGeometry(QtCore.QRect(60, 245, 691, 511))
		hermit_graph = PlotCanvas(self.hermit_graph_box, width=6.9, height=5.1, dpi=100)
		hermit_toolbar = NavigationToolbar(hermit_graph, self.hermit_graph_box)
		hermit_toolbar.move(80, 0)     
		self.hermit_graph_box.setStyleSheet("border: none;\n")
		self.rectangle_box = QtWidgets.QGroupBox(self.hermit)
		self.rectangle_box.setGeometry(QtCore.QRect(120, 30, 400, 150))
		self.rectangle_box.setMinimumSize(QtCore.QSize(400, 150))
		self.rectangle_box.setMaximumSize(QtCore.QSize(400, 150))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(11)
		font.setBold(False)
		font.setWeight(50)
		self.rectangle_box.setFont(font)
		self.rectangle_box.setStyleSheet("background-color:#abff8d;\n"
"border-radius: 5px;")
		self.rectangle_box.setObjectName("rectangle_box")
		self.label_18 = QtWidgets.QLabel(self.rectangle_box)
		self.label_18.setGeometry(QtCore.QRect(120, 50, 10, 30))
		self.label_18.setMinimumSize(QtCore.QSize(10, 30))
		self.label_18.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		self.label_18.setFont(font)
		self.label_18.setObjectName("label_18")
		self.hermit_p1 = QtWidgets.QLineEdit(self.rectangle_box)
		self.hermit_p1.setGeometry(QtCore.QRect(50, 55, 65, 24))
		self.hermit_p1.setMinimumSize(QtCore.QSize(65, 0))
		self.hermit_p1.setMaximumSize(QtCore.QSize(40, 24))
		self.hermit_p1.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.hermit_p1.setText("")
		self.hermit_p1.setObjectName("hermit_p1")
		self.label_17 = QtWidgets.QLabel(self.rectangle_box)
		self.label_17.setGeometry(QtCore.QRect(20, 50, 30, 30))
		self.label_17.setMinimumSize(QtCore.QSize(30, 30))
		self.label_17.setMaximumSize(QtCore.QSize(30, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		self.label_17.setFont(font)
		self.label_17.setObjectName("label_17")
		self.label_19 = QtWidgets.QLabel(self.rectangle_box)
		self.label_19.setGeometry(QtCore.QRect(220, 50, 22, 30))
		self.label_19.setMinimumSize(QtCore.QSize(22, 30))
		self.label_19.setMaximumSize(QtCore.QSize(30, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.label_19.setFont(font)
		self.label_19.setObjectName("label_19")
		self.label_20 = QtWidgets.QLabel(self.rectangle_box)
		self.label_20.setGeometry(QtCore.QRect(320, 50, 10, 30))
		self.label_20.setMinimumSize(QtCore.QSize(10, 30))
		self.label_20.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.label_20.setFont(font)
		self.label_20.setObjectName("label_20")
		self.hermit_p2 = QtWidgets.QLineEdit(self.rectangle_box)
		self.hermit_p2.setGeometry(QtCore.QRect(250, 55, 65, 24))
		self.hermit_p2.setMinimumSize(QtCore.QSize(65, 0))
		self.hermit_p2.setMaximumSize(QtCore.QSize(40, 24))
		self.hermit_p2.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.hermit_p2.setText("")
		self.hermit_p2.setObjectName("hermit_p2")
		self.label_21 = QtWidgets.QLabel(self.rectangle_box)
		self.label_21.setGeometry(QtCore.QRect(20, 100, 30, 30))
		self.label_21.setMinimumSize(QtCore.QSize(30, 30))
		self.label_21.setMaximumSize(QtCore.QSize(30, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.label_21.setFont(font)
		self.label_21.setObjectName("label_21")
		self.label_22 = QtWidgets.QLabel(self.rectangle_box)
		self.label_22.setGeometry(QtCore.QRect(120, 100, 10, 30))
		self.label_22.setMinimumSize(QtCore.QSize(10, 30))
		self.label_22.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.label_22.setFont(font)
		self.label_22.setObjectName("label_22")
		self.hermit_r1 = QtWidgets.QLineEdit(self.rectangle_box)
		self.hermit_r1.setGeometry(QtCore.QRect(50, 105, 65, 24))
		self.hermit_r1.setMinimumSize(QtCore.QSize(65, 0))
		self.hermit_r1.setMaximumSize(QtCore.QSize(40, 24))
		self.hermit_r1.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.hermit_r1.setText("")
		self.hermit_r1.setObjectName("hermit_r1")
		self.label_23 = QtWidgets.QLabel(self.rectangle_box)
		self.label_23.setGeometry(QtCore.QRect(220, 100, 22, 30))
		self.label_23.setMinimumSize(QtCore.QSize(22, 30))
		self.label_23.setMaximumSize(QtCore.QSize(30, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.label_23.setFont(font)
		self.label_23.setObjectName("label_23")
		self.label_24 = QtWidgets.QLabel(self.rectangle_box)
		self.label_24.setGeometry(QtCore.QRect(320, 100, 10, 30))
		self.label_24.setMinimumSize(QtCore.QSize(10, 30))
		self.label_24.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.label_24.setFont(font)
		self.label_24.setObjectName("label_24")
		self.hermit_r2 = QtWidgets.QLineEdit(self.rectangle_box)
		self.hermit_r2.setGeometry(QtCore.QRect(250, 105, 65, 24))
		self.hermit_r2.setMinimumSize(QtCore.QSize(65, 0))
		self.hermit_r2.setMaximumSize(QtCore.QSize(40, 24))
		self.hermit_r2.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.hermit_r2.setText("")
		self.hermit_r2.setObjectName("hermit_r2")
		self.hermit_ok = QtWidgets.QPushButton(self.hermit)
		self.hermit_ok.clicked.connect(lambda: self.hermit_graph_plot(hermit_graph))
		self.hermit_ok.setGeometry(QtCore.QRect(550, 60, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.hermit_ok.setFont(font)
		self.hermit_ok.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.hermit_ok.setObjectName("hermit_ok")
		self.hermit_keyboard_btn = QtWidgets.QPushButton(self.hermit)
		self.hermit_keyboard_btn.setGeometry(QtCore.QRect(550, 110, 100, 40))
		self.hermit_keyboard_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.hermit_keyboard_btn.setText("")
		self.hermit_keyboard_btn.setIcon(icon)
		self.hermit_keyboard_btn.setIconSize(QtCore.QSize(100, 50))
		self.hermit_keyboard_btn.setObjectName("hermit_keyboard_btn")
		self.hermit_keyboard =  None
		self.hermit_keyboard = self.keyboardf(self.hermit, self.hermit_keyboard, (67, 175, 680, 227))
		self.hermit_keyboard_btn.clicked.connect(lambda: self.showorhide(self.hermit_keyboard, (67, 175, 680, 227)))
		self.curves_stacked.addWidget(self.hermit)
		self.ibspline = QtWidgets.QWidget()
		self.ibspline.setObjectName("ibspline")
		self.ibspline_upload_btn = QtWidgets.QPushButton(self.ibspline)
		self.ibspline_upload_btn.setGeometry(QtCore.QRect(580, 100, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.ibspline_upload_btn.setFont(font)
		self.ibspline_upload_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.ibspline_upload_btn.setIcon(icon1)
		self.ibspline_upload_btn.setIconSize(QtCore.QSize(24, 24))
		self.ibspline_upload_btn.setObjectName("ibspline_upload_btn")
		self.groupBox_4 = QtWidgets.QGroupBox(self.ibspline)
		self.groupBox_4.setGeometry(QtCore.QRect(110, 10, 451, 250))
		self.groupBox_4.setMinimumSize(QtCore.QSize(250, 250))
		self.groupBox_4.setMaximumSize(QtCore.QSize(520, 250))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(11)
		self.groupBox_4.setFont(font)
		self.groupBox_4.setStyleSheet("background-color: #abff8d;")
		self.groupBox_4.setObjectName("groupBox_4")
		self.ibspline_p1 = QtWidgets.QLineEdit(self.groupBox_4)
		self.ibspline_p1.setGeometry(QtCore.QRect(70, 35, 65, 24))
		self.ibspline_p1.setMinimumSize(QtCore.QSize(65, 0))
		self.ibspline_p1.setMaximumSize(QtCore.QSize(40, 24))
		self.ibspline_p1.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ibspline_p1.setText("")
		self.ibspline_p1.setObjectName("ibspline_p1")
		self.label_55 = QtWidgets.QLabel(self.groupBox_4)
		self.label_55.setGeometry(QtCore.QRect(40, 30, 22, 30))
		self.label_55.setMinimumSize(QtCore.QSize(22, 30))
		self.label_55.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_55.setFont(font)
		self.label_55.setObjectName("label_55")
		self.label_56 = QtWidgets.QLabel(self.groupBox_4)
		self.label_56.setGeometry(QtCore.QRect(140, 30, 10, 30))
		self.label_56.setMinimumSize(QtCore.QSize(10, 30))
		self.label_56.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_56.setFont(font)
		self.label_56.setObjectName("label_56")
		self.ibspline_p2 = QtWidgets.QLineEdit(self.groupBox_4)
		self.ibspline_p2.setGeometry(QtCore.QRect(205, 35, 65, 24))
		self.ibspline_p2.setMinimumSize(QtCore.QSize(65, 0))
		self.ibspline_p2.setMaximumSize(QtCore.QSize(40, 24))
		self.ibspline_p2.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ibspline_p2.setText("")
		self.ibspline_p2.setObjectName("ibspline_p2")
		self.label_57 = QtWidgets.QLabel(self.groupBox_4)
		self.label_57.setGeometry(QtCore.QRect(275, 30, 10, 30))
		self.label_57.setMinimumSize(QtCore.QSize(10, 30))
		self.label_57.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_57.setFont(font)
		self.label_57.setObjectName("label_57")
		self.label_58 = QtWidgets.QLabel(self.groupBox_4)
		self.label_58.setGeometry(QtCore.QRect(180, 30, 22, 30))
		self.label_58.setMinimumSize(QtCore.QSize(22, 30))
		self.label_58.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_58.setFont(font)
		self.label_58.setObjectName("label_58")
		self.ibspline_p3 = QtWidgets.QLineEdit(self.groupBox_4)
		self.ibspline_p3.setGeometry(QtCore.QRect(335, 35, 65, 24))
		self.ibspline_p3.setMinimumSize(QtCore.QSize(65, 0))
		self.ibspline_p3.setMaximumSize(QtCore.QSize(40, 24))
		self.ibspline_p3.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ibspline_p3.setText("")
		self.ibspline_p3.setObjectName("ibspline_p3")
		self.label_59 = QtWidgets.QLabel(self.groupBox_4)
		self.label_59.setGeometry(QtCore.QRect(405, 30, 10, 30))
		self.label_59.setMinimumSize(QtCore.QSize(10, 30))
		self.label_59.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_59.setFont(font)
		self.label_59.setObjectName("label_59")
		self.label_60 = QtWidgets.QLabel(self.groupBox_4)
		self.label_60.setGeometry(QtCore.QRect(305, 30, 22, 30))
		self.label_60.setMinimumSize(QtCore.QSize(22, 30))
		self.label_60.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_60.setFont(font)
		self.label_60.setObjectName("label_60")
		self.label_61 = QtWidgets.QLabel(self.groupBox_4)
		self.label_61.setGeometry(QtCore.QRect(405, 80, 10, 30))
		self.label_61.setMinimumSize(QtCore.QSize(10, 30))
		self.label_61.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_61.setFont(font)
		self.label_61.setObjectName("label_61")
		self.label_62 = QtWidgets.QLabel(self.groupBox_4)
		self.label_62.setGeometry(QtCore.QRect(305, 80, 22, 30))
		self.label_62.setMinimumSize(QtCore.QSize(22, 30))
		self.label_62.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_62.setFont(font)
		self.label_62.setObjectName("label_62")
		self.label_63 = QtWidgets.QLabel(self.groupBox_4)
		self.label_63.setGeometry(QtCore.QRect(140, 80, 10, 30))
		self.label_63.setMinimumSize(QtCore.QSize(10, 30))
		self.label_63.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_63.setFont(font)
		self.label_63.setObjectName("label_63")
		self.ibspline_p5 = QtWidgets.QLineEdit(self.groupBox_4)
		self.ibspline_p5.setGeometry(QtCore.QRect(205, 85, 65, 24))
		self.ibspline_p5.setMinimumSize(QtCore.QSize(65, 0))
		self.ibspline_p5.setMaximumSize(QtCore.QSize(40, 24))
		self.ibspline_p5.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ibspline_p5.setText("")
		self.ibspline_p5.setObjectName("ibspline_p5")
		self.label_64 = QtWidgets.QLabel(self.groupBox_4)
		self.label_64.setGeometry(QtCore.QRect(40, 80, 22, 30))
		self.label_64.setMinimumSize(QtCore.QSize(22, 30))
		self.label_64.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_64.setFont(font)
		self.label_64.setObjectName("label_64")
		self.label_65 = QtWidgets.QLabel(self.groupBox_4)
		self.label_65.setGeometry(QtCore.QRect(275, 80, 10, 30))
		self.label_65.setMinimumSize(QtCore.QSize(10, 30))
		self.label_65.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_65.setFont(font)
		self.label_65.setObjectName("label_65")
		self.ibspline_p6 = QtWidgets.QLineEdit(self.groupBox_4)
		self.ibspline_p6.setGeometry(QtCore.QRect(335, 85, 65, 24))
		self.ibspline_p6.setMinimumSize(QtCore.QSize(65, 0))
		self.ibspline_p6.setMaximumSize(QtCore.QSize(40, 24))
		self.ibspline_p6.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ibspline_p6.setText("")
		self.ibspline_p6.setObjectName("ibspline_p6")
		self.ibspline_p4 = QtWidgets.QLineEdit(self.groupBox_4)
		self.ibspline_p4.setGeometry(QtCore.QRect(70, 85, 65, 24))
		self.ibspline_p4.setMinimumSize(QtCore.QSize(65, 0))
		self.ibspline_p4.setMaximumSize(QtCore.QSize(40, 24))
		self.ibspline_p4.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ibspline_p4.setText("")
		self.ibspline_p4.setObjectName("ibspline_p4")
		self.label_66 = QtWidgets.QLabel(self.groupBox_4)
		self.label_66.setGeometry(QtCore.QRect(180, 80, 22, 30))
		self.label_66.setMinimumSize(QtCore.QSize(22, 30))
		self.label_66.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_66.setFont(font)
		self.label_66.setObjectName("label_66")
		self.label_67 = QtWidgets.QLabel(self.groupBox_4)
		self.label_67.setGeometry(QtCore.QRect(405, 130, 10, 30))
		self.label_67.setMinimumSize(QtCore.QSize(10, 30))
		self.label_67.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_67.setFont(font)
		self.label_67.setObjectName("label_67")
		self.label_68 = QtWidgets.QLabel(self.groupBox_4)
		self.label_68.setGeometry(QtCore.QRect(305, 130, 22, 30))
		self.label_68.setMinimumSize(QtCore.QSize(22, 30))
		self.label_68.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_68.setFont(font)
		self.label_68.setObjectName("label_68")
		self.label_69 = QtWidgets.QLabel(self.groupBox_4)
		self.label_69.setGeometry(QtCore.QRect(140, 130, 10, 30))
		self.label_69.setMinimumSize(QtCore.QSize(10, 30))
		self.label_69.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_69.setFont(font)
		self.label_69.setObjectName("label_69")
		self.ibspline_p8 = QtWidgets.QLineEdit(self.groupBox_4)
		self.ibspline_p8.setGeometry(QtCore.QRect(205, 135, 65, 24))
		self.ibspline_p8.setMinimumSize(QtCore.QSize(65, 0))
		self.ibspline_p8.setMaximumSize(QtCore.QSize(40, 24))
		self.ibspline_p8.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ibspline_p8.setText("")
		self.ibspline_p8.setObjectName("ibspline_p8")
		self.label_70 = QtWidgets.QLabel(self.groupBox_4)
		self.label_70.setGeometry(QtCore.QRect(40, 130, 22, 30))
		self.label_70.setMinimumSize(QtCore.QSize(22, 30))
		self.label_70.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_70.setFont(font)
		self.label_70.setObjectName("label_70")
		self.label_71 = QtWidgets.QLabel(self.groupBox_4)
		self.label_71.setGeometry(QtCore.QRect(275, 130, 10, 30))
		self.label_71.setMinimumSize(QtCore.QSize(10, 30))
		self.label_71.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_71.setFont(font)
		self.label_71.setObjectName("label_71")
		self.ibspline_p9 = QtWidgets.QLineEdit(self.groupBox_4)
		self.ibspline_p9.setGeometry(QtCore.QRect(335, 135, 65, 24))
		self.ibspline_p9.setMinimumSize(QtCore.QSize(65, 0))
		self.ibspline_p9.setMaximumSize(QtCore.QSize(40, 24))
		self.ibspline_p9.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ibspline_p9.setText("")
		self.ibspline_p9.setObjectName("ibspline_p9")
		self.ibspline_p7 = QtWidgets.QLineEdit(self.groupBox_4)
		self.ibspline_p7.setGeometry(QtCore.QRect(70, 135, 65, 24))
		self.ibspline_p7.setMinimumSize(QtCore.QSize(65, 0))
		self.ibspline_p7.setMaximumSize(QtCore.QSize(40, 24))
		self.ibspline_p7.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ibspline_p7.setText("")
		self.ibspline_p7.setObjectName("ibspline_p7")
		self.label_72 = QtWidgets.QLabel(self.groupBox_4)
		self.label_72.setGeometry(QtCore.QRect(180, 130, 22, 30))
		self.label_72.setMinimumSize(QtCore.QSize(22, 30))
		self.label_72.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_72.setFont(font)
		self.label_72.setObjectName("label_72")
		self.label = QtWidgets.QLabel(self.groupBox_4)
		self.label.setGeometry(QtCore.QRect(50, 160, 111, 21))
		self.label.setObjectName("label")
		self.ibspline_df0 = QtWidgets.QLineEdit(self.groupBox_4)
		self.ibspline_df0.setGeometry(QtCore.QRect(90, 190, 101, 22))
		self.ibspline_df0.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ibspline_df0.setText("")
		self.ibspline_df0.setObjectName("ibspline_df0")
		self.ibspline_ddf0 = QtWidgets.QLineEdit(self.groupBox_4)
		self.ibspline_ddf0.setGeometry(QtCore.QRect(330, 190, 101, 22))
		self.ibspline_ddf0.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ibspline_ddf0.setObjectName("ibspline_ddf0")
		self.ibspline_ddfn = QtWidgets.QLineEdit(self.groupBox_4)
		self.ibspline_ddfn.setGeometry(QtCore.QRect(330, 220, 101, 22))
		self.ibspline_ddfn.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ibspline_ddfn.setObjectName("ibspline_ddfn")
		self.ibspline_dfn = QtWidgets.QLineEdit(self.groupBox_4)
		self.ibspline_dfn.setGeometry(QtCore.QRect(90, 220, 101, 22))
		self.ibspline_dfn.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.ibspline_dfn.setObjectName("ibspline_dfn")
		self.label_2 = QtWidgets.QLabel(self.groupBox_4)
		self.label_2.setGeometry(QtCore.QRect(20, 190, 55, 16))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_2.setFont(font)
		self.label_2.setObjectName("label_2")
		self.label_3 = QtWidgets.QLabel(self.groupBox_4)
		self.label_3.setGeometry(QtCore.QRect(20, 220, 55, 16))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_3.setFont(font)
		self.label_3.setObjectName("label_3")
		self.label_4 = QtWidgets.QLabel(self.groupBox_4)
		self.label_4.setGeometry(QtCore.QRect(260, 190, 55, 16))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_4.setFont(font)
		self.label_4.setObjectName("label_4")
		self.label_5 = QtWidgets.QLabel(self.groupBox_4)
		self.label_5.setGeometry(QtCore.QRect(260, 220, 55, 16))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_5.setFont(font)
		self.label_5.setObjectName("label_5")
		self.label_6 = QtWidgets.QLabel(self.groupBox_4)
		self.label_6.setGeometry(QtCore.QRect(220, 190, 21, 41))
		self.label_6.setObjectName("label_6")
		self.ibspline_new_btn = QtWidgets.QPushButton(self.ibspline)
		self.ibspline_new_btn.setGeometry(QtCore.QRect(580, 50, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.ibspline_new_btn.setFont(font)
		self.ibspline_new_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.ibspline_new_btn.setObjectName("ibspline_new_btn")
		#ibspline plotting
		self.ibspline_graph_box = QtWidgets.QGroupBox(self.ibspline)
		self.ibspline_graph_box.setGeometry(QtCore.QRect(60, 284, 691, 471))
		ibspline_graph = PlotCanvas(self.ibspline_graph_box, width=6.9, height=4.7, dpi=100)
		ibspline_toolbar = NavigationToolbar(ibspline_graph, self.ibspline_graph_box)
		ibspline_toolbar.move(80, 0)		
		self.ibspline_graph_box.setStyleSheet("border: none;\n")
		self.ibspline_ok = QtWidgets.QPushButton(self.ibspline)
		self.ibspline_ok.clicked.connect(lambda: self.ibspline_graph_plot(ibspline_graph))
		self.ibspline_ok.setGeometry(QtCore.QRect(580, 150, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.ibspline_ok.setFont(font)
		self.ibspline_ok.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.ibspline_ok.setObjectName("ibspline_ok")
		self.ibspline_keyboard_btn = QtWidgets.QPushButton(self.ibspline)
		self.ibspline_keyboard_btn.setGeometry(QtCore.QRect(580, 200, 100, 40))
		self.ibspline_keyboard_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.ibspline_keyboard_btn.setText("")
		self.ibspline_keyboard_btn.setIcon(icon)
		self.ibspline_keyboard_btn.setIconSize(QtCore.QSize(100, 50))
		self.ibspline_keyboard_btn.setObjectName("ibspline_keyboard_btn")
		self.ibspline_keyboard = None
		self.ibspline_keyboard = self.keyboardf(self.ibspline, self.ibspline_keyboard, (67, 277, 680, 227))
		self.ibspline_keyboard_btn.clicked.connect(lambda: self.showorhide(self.ibspline_keyboard, (67, 277, 680, 227)))
		self.ibspline_upload_btn.clicked.connect(lambda : self.ibspline_from_upload(ibspline_graph, CurvesMainWindow))
		self.curves_stacked.addWidget(self.ibspline)
		CurvesMainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(CurvesMainWindow)
		self.curves_stacked.setCurrentIndex(2)
		QtCore.QMetaObject.connectSlotsByName(CurvesMainWindow)

	def retranslateUi(self, CurvesMainWindow):
		_translate = QtCore.QCoreApplication.translate
		CurvesMainWindow.setWindowTitle(_translate("CurvesMainWindow", "Computer Graphics - Curves"))
		self.select_hermit.setText(_translate("CurvesMainWindow", "Interpolation Hermitienne"))
		self.select_bezier.setText(_translate("CurvesMainWindow", "Courbes de Bézier"))
		self.select_interb.setText(_translate("CurvesMainWindow", "Interpolation B-Splines"))
		self.select_quit.setText(_translate("CurvesMainWindow", "Back"))
		self.select_approxb.setText(_translate("CurvesMainWindow", "Approximation B-Splines"))
		self.bezier_ok.setText(_translate("CurvesMainWindow", "OK"))
		self.bezier_upload_btn.setText(_translate("CurvesMainWindow", "Upload"))
		self.bezier_new_btn.setText(_translate("CurvesMainWindow", "New"))
		self.groupBox_5.setTitle(_translate("CurvesMainWindow", "Bézier Control Points (2D or 3D)"))
		self.label_73.setText(_translate("CurvesMainWindow", "P1 ("))
		self.label_74.setText(_translate("CurvesMainWindow", ")"))
		self.label_75.setText(_translate("CurvesMainWindow", ")"))
		self.label_76.setText(_translate("CurvesMainWindow", "P2 ("))
		self.label_77.setText(_translate("CurvesMainWindow", ")"))
		self.label_78.setText(_translate("CurvesMainWindow", "P3 ("))
		self.label_79.setText(_translate("CurvesMainWindow", ")"))
		self.label_80.setText(_translate("CurvesMainWindow", "P6 ("))
		self.label_81.setText(_translate("CurvesMainWindow", ")"))
		self.label_82.setText(_translate("CurvesMainWindow", "P4 ("))
		self.label_83.setText(_translate("CurvesMainWindow", ")"))
		self.label_84.setText(_translate("CurvesMainWindow", "P5 ("))
		self.label_85.setText(_translate("CurvesMainWindow", ")"))
		self.label_86.setText(_translate("CurvesMainWindow", "P9 ("))
		self.label_87.setText(_translate("CurvesMainWindow", ")"))
		self.label_88.setText(_translate("CurvesMainWindow", "P7 ("))
		self.label_89.setText(_translate("CurvesMainWindow", ")"))
		self.label_90.setText(_translate("CurvesMainWindow", "P8 ("))
		self.abspline_ok.setText(_translate("CurvesMainWindow", "OK"))
		self.abspline_upload_btn.setText(_translate("CurvesMainWindow", "Upload"))
		self.abspline_new_btn.setText(_translate("CurvesMainWindow", "New"))
		self.groupBox_6.setTitle(_translate("CurvesMainWindow", "Approximation B-Splines Control Points (2D or 3D)"))
		self.label_91.setText(_translate("CurvesMainWindow", "P1 ("))
		self.label_92.setText(_translate("CurvesMainWindow", ")"))
		self.label_93.setText(_translate("CurvesMainWindow", ")"))
		self.label_94.setText(_translate("CurvesMainWindow", "P2 ("))
		self.label_95.setText(_translate("CurvesMainWindow", ")"))
		self.label_96.setText(_translate("CurvesMainWindow", "P3 ("))
		self.label_97.setText(_translate("CurvesMainWindow", ")"))
		self.label_98.setText(_translate("CurvesMainWindow", "P6 ("))
		self.label_99.setText(_translate("CurvesMainWindow", ")"))
		self.label_100.setText(_translate("CurvesMainWindow", "P4 ("))
		self.label_101.setText(_translate("CurvesMainWindow", ")"))
		self.label_102.setText(_translate("CurvesMainWindow", "P5 ("))
		self.label_103.setText(_translate("CurvesMainWindow", ")"))
		self.label_104.setText(_translate("CurvesMainWindow", "P9 ("))
		self.label_105.setText(_translate("CurvesMainWindow", ")"))
		self.label_106.setText(_translate("CurvesMainWindow", "P7 ("))
		self.label_107.setText(_translate("CurvesMainWindow", ")"))
		self.label_108.setText(_translate("CurvesMainWindow", "P8 ("))
		self.rectangle_box.setTitle(_translate("CurvesMainWindow", "Control Points (2D)"))
		self.label_18.setText(_translate("CurvesMainWindow", ")"))
		self.label_17.setText(_translate("CurvesMainWindow", "P1 ("))
		self.label_19.setText(_translate("CurvesMainWindow", "P2("))
		self.label_20.setText(_translate("CurvesMainWindow", ")"))
		self.label_21.setText(_translate("CurvesMainWindow", "R1("))
		self.label_22.setText(_translate("CurvesMainWindow", ")"))
		self.label_23.setText(_translate("CurvesMainWindow", "R2("))
		self.label_24.setText(_translate("CurvesMainWindow", ")"))
		self.hermit_ok.setText(_translate("CurvesMainWindow", "OK"))
		self.ibspline_upload_btn.setText(_translate("CurvesMainWindow", "Upload"))
		self.groupBox_4.setTitle(_translate("CurvesMainWindow", "Interpolation B-Splines Control Points (2D)"))
		self.label_55.setText(_translate("CurvesMainWindow", "P1 ("))
		self.label_56.setText(_translate("CurvesMainWindow", ")"))
		self.label_57.setText(_translate("CurvesMainWindow", ")"))
		self.label_58.setText(_translate("CurvesMainWindow", "P2 ("))
		self.label_59.setText(_translate("CurvesMainWindow", ")"))
		self.label_60.setText(_translate("CurvesMainWindow", "P3 ("))
		self.label_61.setText(_translate("CurvesMainWindow", ")"))
		self.label_62.setText(_translate("CurvesMainWindow", "P6 ("))
		self.label_63.setText(_translate("CurvesMainWindow", ")"))
		self.label_64.setText(_translate("CurvesMainWindow", "P4 ("))
		self.label_65.setText(_translate("CurvesMainWindow", ")"))
		self.label_66.setText(_translate("CurvesMainWindow", "P5 ("))
		self.label_67.setText(_translate("CurvesMainWindow", ")"))
		self.label_68.setText(_translate("CurvesMainWindow", "P9 ("))
		self.label_69.setText(_translate("CurvesMainWindow", ")"))
		self.label_70.setText(_translate("CurvesMainWindow", "P7 ("))
		self.label_71.setText(_translate("CurvesMainWindow", ")"))
		self.label_72.setText(_translate("CurvesMainWindow", "P8 ("))
		self.label.setText(_translate("CurvesMainWindow", "Boundry Conditions"))
		self.ibspline_ddf0.setText(_translate("CurvesMainWindow", "2"))
		self.ibspline_ddfn.setText(_translate("CurvesMainWindow", "1"))
		self.ibspline_dfn.setText(_translate("CurvesMainWindow", "5"))
		self.label_2.setText(_translate("CurvesMainWindow", "S\'(x0) ="))
		self.label_3.setText(_translate("CurvesMainWindow", "S\'(xn) ="))
		self.label_4.setText(_translate("CurvesMainWindow", "S\'\'(x0) ="))
		self.label_5.setText(_translate("CurvesMainWindow", "s\"(xn) ="))
		self.label_6.setText(_translate("CurvesMainWindow", "Or"))
		self.ibspline_new_btn.setText(_translate("CurvesMainWindow", "New"))
		self.ibspline_ok.setText(_translate("CurvesMainWindow", "OK"))
		self.select_quit.clicked.connect(CurvesMainWindow.close)
		self.ibspline_new_btn.clicked.connect(self.ibspline_page)
		self.select_interb.clicked.connect(self.ibspline_page)
		self.abspline_new_btn.clicked.connect(self.abspline_page)
		self.select_approxb.clicked.connect(self.abspline_page)
		self.bezier_new_btn.clicked.connect(self.bezier_page)
		self.select_bezier.clicked.connect(self.bezier_page)
		self.select_hermit.clicked.connect(self.hermit_page)

	def missing_data_dialog(self, text):
		msg = QMessageBox()
		msg.setIcon(QMessageBox.Warning)
		msg.setText(f"Entrer {text}!!")
		msg.setWindowTitle("Error!")
		msg.setStandardButtons(QMessageBox.Ok)
		msg.exec_()

	def wrong_expr_dialog(self, text):
		msg = QMessageBox()
		msg.setIcon(QMessageBox.Warning)
		msg.setText(f"Expression de {text} est fausse!!")
		msg.setWindowTitle("Error!")
		msg.setStandardButtons(QMessageBox.Ok)
		msg.exec_()

	def limit_exceed_dialog(self):
		msg = QMessageBox()
		msg.setIcon(QMessageBox.Warning)
		msg.setText(f"2D ou 3D seulement")
		msg.setWindowTitle("Error!")
		msg.setStandardButtons(QMessageBox.Ok)
		msg.exec_()

	def normalize_formula(self, formula, text):
		formula =  formula.split(',')
		formula = [formula[i].replace('^', '**').replace('π', 'pi') for i in range(len(formula))]
		formula  = tuple(formula)
		try:
			formula = [eval(formula[i]) for i in range(len(formula))]
			formula = tuple(formula)
		except Exception:
			self.wrong_expr_dialog(text)
			return None
		return formula

	def normalize_formula_1d(self, formula, text):
		formula = formula.replace('^', '**')
		formula = formula.replace('π', 'pi')
		try:
			formula = eval(formula)
		except Exception:
			self.wrong_expr_dialog(text)
			return None
		return formula

	def bezier_from_upload(self, bezier_graph, CurvesMainwindow):
		options = QFileDialog.Options()
		options |= QFileDialog.DontUseNativeDialog
		fileName, _ = QFileDialog.getOpenFileName(CurvesMainwindow,"QFileDialog.getOpenFileName()", "","CSV Files (*.csv)", options=options)
		if fileName:
			points = generate_from_file(fileName)
			bezier_graph.plot_bezier(points)
			
	def bezier_graph_plot(self, bezier_graph):
		p1, p2, p3 = self.bezier_p1.text(), self.bezier_p2.text(), self.bezier_p3.text()
		p4, p5, p6 = self.bezier_p4.text(), self.bezier_p5.text(), self.bezier_p6.text()
		p7, p8, p9 = self.bezier_p7.text(), self.bezier_p8.text(), self.bezier_p9.text()
		if (len(p1) == 0) or (len(p2) == 0) or (len(p3) == 0) :
			self.missing_data_dialog('au moins P1, P2, et P3')
			return
		points = [p1, p2, p3, p4, p5, p6, p7, p8, p9]
		i = 0
		while i < 9 and len(points[i]) > 0:
			points[i] = self.normalize_formula(points[i], f'p{i+1}')
			i += 1
		if i < 9:
			points = points[:i]
		if len(points[0]) > 3:
			self.limit_exceed_dialog()
			return			
		test = 1
		for j in range(i):
			if points[j] == None:
				test = 0
				break
		if (test):
			self.bezier_keyboard.setMinimumSize(QtCore.QSize(680, 227))
			self.showorhide(self.bezier_keyboard, (67, 220, 680, 227))
			points = np.array(points)
			bezier_graph.plot_bezier(points)

	def abspline_from_upload(self, abspline_graph, CurvesMainwindow):
		options = QFileDialog.Options()
		options |= QFileDialog.DontUseNativeDialog
		fileName, _ = QFileDialog.getOpenFileName(CurvesMainwindow,"QFileDialog.getOpenFileName()", "","CSV Files (*.csv)", options=options)
		if fileName:
			points = generate_from_file(fileName)
			abspline_graph.plot_abspline(points)

	def abspline_graph_plot(self, abspline_graph):
		p1, p2, p3 = self.abspline_p1.text(), self.abspline_p2.text(), self.abspline_p3.text()
		p4, p5, p6 = self.abspline_p4.text(), self.abspline_p5.text(), self.abspline_p6.text()
		p7, p8, p9 = self.abspline_p7.text(), self.abspline_p8.text(), self.abspline_p9.text()
		if (len(p1) == 0) or (len(p2) == 0) or (len(p3) == 0) :
			self.missing_data_dialog('au moins P1, P2, et P3')
			return
		points = [p1, p2, p3, p4, p5, p6, p7, p8, p9]
		i = 0
		while i < 9 and len(points[i]) > 0:
			points[i] = self.normalize_formula(points[i], f'p{i+1}')
			i += 1
		if i < 9:
			points = points[:i]
		if len(points[0]) > 3:
			self.limit_exceed_dialog()
			return
		test = 1
		for j in range(i):
			if points[j] == None:
				test = 0
				break
		if (test):
			self.abspline_keyboard.setMinimumSize(QtCore.QSize(680, 227))
			self.showorhide(self.abspline_keyboard, (67, 220, 680, 227))
			points = np.array(points)
			abspline_graph.plot_abspline(points)

	def ibspline_from_upload(self, ibspline_graph, CurvesMainwindow):
		df0, dfn = self.ibspline_df0.text(), self.ibspline_dfn.text()
		ddf0, ddfn = self.ibspline_ddf0.text(), self.ibspline_ddfn.text()
		if (len(df0) > 0) and (len(dfn) > 0):
			boundry_condition = 1
			c1 = df0
			c2 = dfn
		elif (len(ddf0) > 0) and (len(ddfn) > 0):
			boundry_condition = 2
			c1 = ddf0
			c2 = ddfn
		else:
			self.missing_data_dialog('Boundry Conditions')
			return
		test = 1
		c1 = self.normalize_formula_1d(c1, "Boundry Condition 1")
		c2 = self.normalize_formula_1d(c2, "Boundry Condition 2")
		if c1 == None or c2 ==None:
			test = 0
		if (test):	
			options = QFileDialog.Options()
			options |= QFileDialog.DontUseNativeDialog
			fileName, _ = QFileDialog.getOpenFileName(CurvesMainwindow,"QFileDialog.getOpenFileName()", "","CSV Files (*.csv)", options=options)
			if fileName:
				points = generate_from_file(fileName)
				ibspline_graph.plot_ibspline(points, boundry_condition, c1, c2)

	def ibspline_graph_plot(self, ibspline_graph):
		p1, p2, p3 = self.ibspline_p1.text(), self.ibspline_p2.text(), self.ibspline_p3.text()
		p4, p5, p6 = self.ibspline_p4.text(), self.ibspline_p5.text(), self.ibspline_p6.text()
		p7, p8, p9 = self.ibspline_p7.text(), self.ibspline_p8.text(), self.ibspline_p9.text()
		df0, dfn = self.ibspline_df0.text(), self.ibspline_dfn.text()
		ddf0, ddfn = self.ibspline_ddf0.text(), self.ibspline_ddfn.text()
		if (len(p1) == 0) or (len(p2) == 0) or (len(p3) == 0) :
			self.missing_data_dialog('au moins P1, P2, et P3')
			return
		if (len(df0) > 0) and (len(dfn) > 0):
			boundry_condition = 1
			c1 = df0
			c2 = dfn
		elif (len(ddf0) > 0) and (len(ddfn) > 0):
			boundry_condition = 2
			c1 = ddf0
			c2 = ddfn
		else:
			self.missing_data_dialog('Boundry Conditions')
			return
		points = [p1, p2, p3, p4, p5, p6, p7, p8, p9]
		i = 0
		while i < 9 and len(points[i]) > 0:
			points[i] = self.normalize_formula(points[i], f'p{i+1}')
			i += 1
		if i < 9:
			points = points[:i]
		if len(points[0]) > 3:
			self.limit_exceed_dialog()
			return
		test = 1
		for j in range(i):
			if points[j] == None:
				test = 0
				break
		c1 = self.normalize_formula_1d(c1, "Boundry Condition 1")
		c2 = self.normalize_formula_1d(c2, "Boundry Condition 2")
		if c1 == None or c2 ==None:
			test = 0
		if (test):
			self.ibspline_keyboard.setMinimumSize(QtCore.QSize(680, 227))
			self.showorhide(self.ibspline_keyboard, (67, 220, 680, 227))
			points = np.array(points)
			ibspline_graph.plot_ibspline(points, boundry_condition, c1, c2)
			
	def hermit_graph_plot(self, hermit_graph):
		p1, p2 = self.hermit_p1.text(), self.hermit_p2.text()
		r1, r2 = self.hermit_r1.text(), self.hermit_r2.text()
		if (len(p1) == 0) or (len(p2) == 0) or (len(r1) == 0) or (len(r2) == 0):
			self.missing_data_dialog('Tous les données')
			return
		points = [p1, p2, r1, r2]
		test = 1
		for i in range(4):
			points[i] = self.normalize_formula(points[i], f'p{i+1}')
			if points[i] == None:
				test = 0
				break;
		if (test):
			self.hermit_keyboard.setMinimumSize(QtCore.QSize(680, 227))
			self.showorhide(self.hermit_keyboard, (67, 175, 680, 227))
			data = (points[0][0], points[1][0], points[0][1], points[1][1], points[2][1], points[3][1])
			hermit_graph.plot_hermit(data)

	def clear_all_inputs(self):
		listsMyQLineEdit = self.centralwidget.findChildren(QLineEdit)
		for myQLineEdit in listsMyQLineEdit:
			myQLineEdit.clear()

	def bezier_page(self):
		self.curves_stacked.setCurrentIndex(0)
		self.new = True
		self.clear_all_inputs()

	def hermit_page(self):
		self.curves_stacked.setCurrentIndex(2)
		self.new = True
		self.clear_all_inputs()

	def abspline_page(self):
		self.curves_stacked.setCurrentIndex(1)
		self.new = True
		self.clear_all_inputs()

	def ibspline_page(self):
		self.curves_stacked.setCurrentIndex(3)
		self.new = True
		self.clear_all_inputs()

	def setFocusOnLast(self):
		widget = QtWidgets.QApplication.instance().inputFocusWidget()
		if widget:
			return widget

	def toinput(self, text, name):
		widget_input = self.setFocusOnLast() if not self.new else None
		self.new = False
		if widget_input is None:
			widget_input = self.bezier_p1 if (name == self.bezier_keyboard) else self.abspline_p1 if (name == self.abspline_keyboard) else self.ibspline_p1 if (name == self.ibspline_keyboard) else self.hermit_keyboard
		widget_input.setFocus()
		self.input_value(text, widget_input)

	def showorhide(self, widget, geometry):
		if widget.height() == 0:
			widget.setGeometry(QtCore.QRect(*geometry))
			widget.setMinimumSize(QtCore.QSize(680, 227))
			widget.setMaximumSize(QtCore.QSize(680, 227))
		else:
			widget.setMinimumSize(QtCore.QSize(0, 0))
			widget.setMaximumSize(QtCore.QSize(0, 0))
			widget.setGeometry(QtCore.QRect(0, 0, 0, 0))

	def input_value(self, v, input):
		input.setText(input.text()[:input.cursorPosition()] + v + input.text()[input.cursorPosition():]) 

	def keyboardf(self, parent, name, geometry):
		_translate = QtCore.QCoreApplication.translate
		name = QtWidgets.QGroupBox(parent)
		name.setGeometry(QtCore.QRect(0, 0, 0, 0))
		name.setStyleSheet("*{\n"
"    padding: 20px;\n"
"    background-color: #ccc;\n"
"}\n"
"QPushButton {\n"
"    padding: 0px;\n"
"    background-color: #fdfdfd;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 8px;\n"
"    font: 20px \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(240, 240, 240);\n"
"}")
		name.setTitle("")
		name.setObjectName("keyboard")
		self.numbers = QtWidgets.QGroupBox(name)
		self.numbers.setGeometry(QtCore.QRect(250, 2, 412, 220))
		self.numbers.setMinimumSize(QtCore.QSize(412, 220))
		self.numbers.setMaximumSize(QtCore.QSize(412, 220))
		self.numbers.setStyleSheet("border: none;")
		self.numbers.setTitle("")
		self.numbers.setObjectName("numbers")
		self.btn_7 = QtWidgets.QPushButton(self.numbers)
		self.btn_7.setGeometry(QtCore.QRect(0, 5, 100, 50))
		self.btn_7.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_7.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_7.setObjectName("btn_7")
		self.btn_7.setText(_translate("BresnhamMainWindow", "7"))
		self.btn_7.clicked.connect(lambda: self.toinput('7', name))
		self.btn_8 = QtWidgets.QPushButton(self.numbers)
		self.btn_8.setGeometry(QtCore.QRect(104, 5, 100, 50))
		self.btn_8.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_8.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_8.setObjectName("btn_8")
		self.btn_8.setText(_translate("BresnhamMainWindow", "8"))
		self.btn_8.clicked.connect(lambda: self.toinput('8', name))
		self.btn_9 = QtWidgets.QPushButton(self.numbers)
		self.btn_9.setGeometry(QtCore.QRect(208, 5, 100, 50))
		self.btn_9.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_9.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_9.setObjectName("btn_9")
		self.btn_9.setText(_translate("BresnhamMainWindow", "9"))
		self.btn_9.clicked.connect(lambda: self.toinput('9', name))
		self.divide_btn = QtWidgets.QPushButton(self.numbers)
		self.divide_btn.setGeometry(QtCore.QRect(312, 5, 100, 50))
		self.divide_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.divide_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.divide_btn.setObjectName("divide_btn")
		self.divide_btn.setText(_translate("BresnhamMainWindow", "/"))
		self.divide_btn.clicked.connect(lambda: self.toinput('/', name))
		self.btn_5 = QtWidgets.QPushButton(self.numbers)
		self.btn_5.setGeometry(QtCore.QRect(104, 60, 100, 50))
		self.btn_5.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_5.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_5.setObjectName("btn_5")
		self.btn_5.setText(_translate("BresnhamMainWindow", "5"))
		self.btn_5.clicked.connect(lambda: self.toinput('5', name))
		self.btn_4 = QtWidgets.QPushButton(self.numbers)
		self.btn_4.setGeometry(QtCore.QRect(0, 60, 100, 50))
		self.btn_4.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_4.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_4.setObjectName("btn_4")
		self.btn_4.setText(_translate("BresnhamMainWindow", "4"))
		self.btn_4.clicked.connect(lambda: self.toinput('4', name))
		self.btn_6 = QtWidgets.QPushButton(self.numbers)
		self.btn_6.setGeometry(QtCore.QRect(208, 60, 100, 50))
		self.btn_6.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_6.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_6.setObjectName("btn_6")
		self.btn_6.setText(_translate("BresnhamMainWindow", "6"))
		self.btn_6.clicked.connect(lambda: self.toinput('6', name))
		self.multiply_btn = QtWidgets.QPushButton(self.numbers)
		self.multiply_btn.setGeometry(QtCore.QRect(312, 60, 100, 50))
		self.multiply_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.multiply_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.multiply_btn.setObjectName("multiply_btn")
		self.multiply_btn.setText(_translate("BresnhamMainWindow", "x"))
		self.multiply_btn.clicked.connect(lambda: self.toinput('*', name))
		self.btn_2 = QtWidgets.QPushButton(self.numbers)
		self.btn_2.setGeometry(QtCore.QRect(104, 115, 100, 50))
		self.btn_2.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_2.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_2.setObjectName("btn_2")
		self.btn_2.setText(_translate("BresnhamMainWindow", "2"))
		self.btn_2.clicked.connect(lambda: self.toinput('2', name))
		self.btn_1 = QtWidgets.QPushButton(self.numbers)
		self.btn_1.setGeometry(QtCore.QRect(0, 115, 100, 50))
		self.btn_1.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_1.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_1.setObjectName("btn_1")
		self.btn_1.setText(_translate("BresnhamMainWindow", "1"))
		self.btn_1.clicked.connect(lambda: self.toinput('1', name))
		self.btn_3 = QtWidgets.QPushButton(self.numbers)
		self.btn_3.setGeometry(QtCore.QRect(208, 115, 100, 50))
		self.btn_3.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_3.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_3.setObjectName("btn_3")
		self.btn_3.setText(_translate("BresnhamMainWindow", "3"))
		self.btn_3.clicked.connect(lambda: self.toinput('3', name))
		self.minus_btn = QtWidgets.QPushButton(self.numbers)
		self.minus_btn.setGeometry(QtCore.QRect(312, 115, 100, 50))
		self.minus_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.minus_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.minus_btn.setObjectName("minus_btn")
		self.minus_btn.setText(_translate("BresnhamMainWindow", "-"))
		self.minus_btn.clicked.connect(lambda: self.toinput('-', name))
		self.btn_0 = QtWidgets.QPushButton(self.numbers)
		self.btn_0.setGeometry(QtCore.QRect(0, 170, 204, 50))
		self.btn_0.setMinimumSize(QtCore.QSize(204, 50))
		self.btn_0.setMaximumSize(QtCore.QSize(204, 50))
		self.btn_0.setObjectName("btn_0")
		self.btn_0.setText(_translate("BresnhamMainWindow", "0"))
		self.btn_0.clicked.connect(lambda: self.toinput('0', name))
		self.comma_btn = QtWidgets.QPushButton(self.numbers)
		self.comma_btn.setGeometry(QtCore.QRect(208, 170, 100, 50))
		self.comma_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.comma_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.comma_btn.setObjectName("comma_btn")
		self.comma_btn.setText(_translate("BresnhamMainWindow", "."))
		self.comma_btn.clicked.connect(lambda: self.toinput('.', name))
		self.plus_btn = QtWidgets.QPushButton(self.numbers)
		self.plus_btn.setGeometry(QtCore.QRect(312, 170, 100, 50))
		self.plus_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.plus_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.plus_btn.setObjectName("plus_btn")
		self.plus_btn.setText(_translate("BresnhamMainWindow", "+"))
		self.plus_btn.clicked.connect(lambda: self.toinput('+', name))
		self.characters = QtWidgets.QGroupBox(name)
		self.characters.setGeometry(QtCore.QRect(10, 2, 212, 220))
		self.characters.setMinimumSize(QtCore.QSize(212, 220))
		self.characters.setMaximumSize(QtCore.QSize(212, 220))
		self.characters.setStyleSheet("border: none;")
		self.characters.setTitle("")
		self.characters.setObjectName("characters")
		self.pi_btn = QtWidgets.QPushButton(self.characters)
		self.pi_btn.setGeometry(QtCore.QRect(0, 5, 104, 50))
		self.pi_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.pi_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.pi_btn.setObjectName("pi_btn")
		self.pi_btn.setText(_translate("BresnhamMainWindow", "π"))
		self.pi_btn.clicked.connect(lambda: self.toinput('π', name))
		self.square_btn = QtWidgets.QPushButton(self.characters)
		self.square_btn.setGeometry(QtCore.QRect(108, 5, 104, 50))
		self.square_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.square_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.square_btn.setObjectName("square_btn")
		self.square_btn.setText(_translate("BresnhamMainWindow", "a²"))
		self.square_btn.clicked.connect(lambda: self.toinput('^2', name))
		self.sqrt_btn = QtWidgets.QPushButton(self.characters)
		self.sqrt_btn.setGeometry(QtCore.QRect(0, 60, 104, 50))
		self.sqrt_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.sqrt_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.sqrt_btn.setObjectName("sqrt_btn")
		self.sqrt_btn.setText(_translate("BresnhamMainWindow", "√"))
		self.sqrt_btn.clicked.connect(lambda: self.toinput('sqrt(', name))
		self.power_btn = QtWidgets.QPushButton(self.characters)
		self.power_btn.setGeometry(QtCore.QRect(108, 60, 104, 50))
		self.power_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.power_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.power_btn.setObjectName("power_btn")
		self.power_btn.setText(_translate("BresnhamMainWindow", "aⁿ"))
		self.power_btn.clicked.connect(lambda: self.toinput('^', name))
		self.left_btn = QtWidgets.QPushButton(self.characters)
		self.left_btn.setGeometry(QtCore.QRect(0, 115, 104, 50))
		self.left_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.left_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.left_btn.setObjectName("left_btn")
		self.left_btn.setText(_translate("BresnhamMainWindow", "("))
		self.left_btn.clicked.connect(lambda: self.toinput('(', name))
		self.right_btn = QtWidgets.QPushButton(self.characters)
		self.right_btn.setGeometry(QtCore.QRect(108, 115, 104, 50))
		self.right_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.right_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.right_btn.setObjectName("right_btn")
		self.right_btn.clicked.connect(lambda: self.toinput(')', name))
		self.right_btn.setText(_translate("BresnhamMainWindow", ")"))
		self.exp_btn = QtWidgets.QPushButton(self.characters)
		self.exp_btn.setGeometry(QtCore.QRect(0, 170, 104, 50))
		self.exp_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.exp_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.exp_btn.setObjectName("exp_btn")
		self.exp_btn.setText(_translate("BresnhamMainWindow", "eⁿ"))
		self.exp_btn.clicked.connect(lambda: self.toinput('exp(', name))
		self.pof10_btn = QtWidgets.QPushButton(self.characters)
		self.pof10_btn.setGeometry(QtCore.QRect(108, 170, 104, 50))
		self.pof10_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.pof10_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.pof10_btn.setObjectName("pof10_btn")
		self.pof10_btn.setText(_translate("BresnhamMainWindow", "10ⁿ"))
		self.pof10_btn.clicked.connect(lambda: self.toinput('10^', name))
		return name
import resources


if __name__ == "__main__":
	import sys
	app = MyApplication(sys.argv)
	CurvesMainWindow = QtWidgets.QMainWindow()
	ui = Ui_CurvesMainWindow()
	ui.setupUi(CurvesMainWindow)
	CurvesMainWindow.show()
	sys.exit(app.exec_())
