#coding: utf-8

import matplotlib
matplotlib.use('Qt5Agg')
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, QEvent, pyqtSignal
from PyQt5.QtWidgets import (QWidget, QLineEdit, QLabel, QPushButton, QSizePolicy, QMessageBox, QFileDialog)
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas , NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
import numpy as np
from math import *
from remplissage import filling, plot_polygone, generate_from_file


class PlotCanvas(FigureCanvas):
	def __init__(self, parent = None, width = 5, height = 4, dpi = 100):
		fig = Figure(figsize = (width, height), dpi= dpi)
		self.ax1 = fig.add_subplot(121)
		self.ax2 = fig.add_subplot(122)
		FigureCanvas.__init__(self, fig)
		self.setParent(parent)
		FigureCanvas.setSizePolicy(self, QSizePolicy.Expanding, QSizePolicy.Expanding)
		FigureCanvas.updateGeometry(self)

	def plot_poly(self, poly, data):
		self.ax1.cla()
		self.ax2.cla()
		self.ax1.set_title('Before')
		self.ax2.set_title('After')
		plot_polygone(self.ax1, poly, 'r')
		plot_polygone(self.ax2, poly, 'r')
		for x , y  in data:
			self.ax2.scatter(x, y, c='yellow')
		self.draw()

	
class inputFocusFilter(QObject):
	focusIn = pyqtSignal(object)
	def eventFilter(self, widget, event):
		if event.type() == QEvent.FocusIn and isinstance(widget, QLineEdit):
			self.focusIn.emit(widget)
		return super(inputFocusFilter, self).eventFilter(widget, event)


class MyApplication(QtWidgets.QApplication):
	def __init__(self, *arg, **kwarg):
		super(MyApplication, self).__init__(*arg, **kwarg)

		self._input_focus_widget = None

		self.event_filter = inputFocusFilter()
		self.event_filter.focusIn.connect(self.setInputFocusWidget)
		self.installEventFilter(self.event_filter)

	def setInputFocusWidget(self, widget):
		self._input_focus_widget = widget

	def inputFocusWidget(self):
		return self._input_focus_widget



class Ui_ScanLineMainWindow(object):
	def __init__(self):
		self.n = 3
		self.geometry = np.array([[15, 30, 22, 30], [45, 35, 65, 24], [115, 30, 10, 30]])
		self.stepx = np.array([[145, 0, 0, 0], [145, 0, 0, 0], [145, 0, 0, 0]])
		self.stepy = np.array([[0, 35, 0, 0], [0, 35, 0, 0], [0, 35, 0, 0]])
		self.points_btns = []
	def setupUi(self, ScanLineMainWindow):
		ScanLineMainWindow.setObjectName("ScanLineMainWindow")
		ScanLineMainWindow.resize(1024, 768)
		ScanLineMainWindow.setMinimumSize(QtCore.QSize(1024, 768))
		ScanLineMainWindow.setMaximumSize(QtCore.QSize(1024, 768))
		ScanLineMainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("cg.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		ScanLineMainWindow.setWindowIcon(icon)		
		self.centralwidget = QtWidgets.QWidget(ScanLineMainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.scanline_menu = QtWidgets.QGroupBox(self.centralwidget)
		self.scanline_menu.setGeometry(QtCore.QRect(0, 0, 200, 768))
		self.scanline_menu.setMinimumSize(QtCore.QSize(200, 768))
		self.scanline_menu.setMaximumSize(QtCore.QSize(200, 768))
		self.scanline_menu.setStyleSheet("*{\n"
"    background-color: #87ffcd;\n"
"    margin: 0;\n"
"    width: 100%;\n"
"    height: 100%\n"
"}\n"
"QPushButton {\n"
"    min-width: 100%;\n"
"    margin: 0;\n"
"    padding: 10px;\n"
"    font: 75 16px \"MS Shell Dlg 2\";\n"
"    height: auto;\n"
"    outline: None; \n"
"    border: None\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #5c49d6;\n"
"    color: #fff\n"
"}")
		self.scanline_menu.setTitle("")
		self.scanline_menu.setObjectName("scanline_menu")
		self.select_segment = QtWidgets.QPushButton(self.scanline_menu)
		self.select_segment.setGeometry(QtCore.QRect(0, 15, 200, 60))
		self.select_segment.setMinimumSize(QtCore.QSize(120, 60))
		self.select_segment.setMaximumSize(QtCore.QSize(200, 60))
		self.select_segment.setStyleSheet("")
		self.select_segment.setObjectName("select_segment")
		self.select_quit = QtWidgets.QPushButton(self.scanline_menu)
		self.select_quit.setGeometry(QtCore.QRect(0, 600, 200, 60))
		self.select_quit.setMinimumSize(QtCore.QSize(120, 60))
		self.select_quit.setMaximumSize(QtCore.QSize(200, 60))
		self.select_quit.setStyleSheet("")
		self.select_quit.setObjectName("select_quit")
		self.select_quit.clicked.connect(ScanLineMainWindow.close)
		self.remplissage_new_btn = QtWidgets.QPushButton(self.centralwidget)
		self.remplissage_new_btn.clicked.connect(self.clear_all_inputs)
		self.remplissage_new_btn.setGeometry(QtCore.QRect(740, 22, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.remplissage_new_btn.setFont(font)
		self.remplissage_new_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.remplissage_new_btn.setObjectName("remplissage_new_btn")
		self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
		self.groupBox_2.setGeometry(QtCore.QRect(310, 37, 420, 170))
		self.groupBox_2.setMinimumSize(QtCore.QSize(420, 170))
		self.groupBox_2.setMaximumSize(QtCore.QSize(420, 170))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(11)
		self.groupBox_2.setFont(font)
		self.groupBox_2.setStyleSheet("background-color: #abff8d;")
		self.groupBox_2.setTitle("")
		self.groupBox_2.setObjectName("groupBox_2")
		self.remplissage_p1 = QtWidgets.QLineEdit(self.groupBox_2)
		self.remplissage_p1.setGeometry(QtCore.QRect(45, 35, 65, 24))
		self.remplissage_p1.setMinimumSize(QtCore.QSize(65, 24))
		self.remplissage_p1.setMaximumSize(QtCore.QSize(65, 24))
		self.remplissage_p1.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.remplissage_p1.setText("")
		self.remplissage_p1.setObjectName("remplissage_p1")
		self.label_17 = QtWidgets.QLabel(self.groupBox_2)
		self.label_17.setGeometry(QtCore.QRect(15, 30, 22, 30))
		self.label_17.setMinimumSize(QtCore.QSize(22, 30))
		self.label_17.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_17.setFont(font)
		self.label_17.setObjectName("label_17")
		self.label_18 = QtWidgets.QLabel(self.groupBox_2)
		self.label_18.setGeometry(QtCore.QRect(115, 30, 10, 30))
		self.label_18.setMinimumSize(QtCore.QSize(10, 30))
		self.label_18.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_18.setFont(font)
		self.label_18.setObjectName("label_18")
		self.remplissage_p2 = QtWidgets.QLineEdit(self.groupBox_2)
		self.remplissage_p2.setGeometry(QtCore.QRect(185, 35, 65, 24))
		self.remplissage_p2.setMinimumSize(QtCore.QSize(65, 24))
		self.remplissage_p2.setMaximumSize(QtCore.QSize(65, 24))
		self.remplissage_p2.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.remplissage_p2.setText("")
		self.remplissage_p2.setObjectName("remplissage_p2")
		self.label_19 = QtWidgets.QLabel(self.groupBox_2)
		self.label_19.setGeometry(QtCore.QRect(255, 30, 10, 30))
		self.label_19.setMinimumSize(QtCore.QSize(10, 30))
		self.label_19.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_19.setFont(font)
		self.label_19.setObjectName("label_19")
		self.label_20 = QtWidgets.QLabel(self.groupBox_2)
		self.label_20.setGeometry(QtCore.QRect(155, 30, 22, 30))
		self.label_20.setMinimumSize(QtCore.QSize(22, 30))
		self.label_20.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_20.setFont(font)
		self.label_20.setObjectName("label_20")
		self.remplissage_p3 = QtWidgets.QLineEdit(self.groupBox_2)
		self.remplissage_p3.setGeometry(QtCore.QRect(325, 35, 65, 24))
		self.remplissage_p3.setMinimumSize(QtCore.QSize(65, 24))
		self.remplissage_p3.setMaximumSize(QtCore.QSize(65, 24))
		self.remplissage_p3.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.remplissage_p3.setText("")
		self.remplissage_p3.setObjectName("remplissage_p3")
		self.label_21 = QtWidgets.QLabel(self.groupBox_2)
		self.label_21.setGeometry(QtCore.QRect(400, 30, 10, 30))
		self.label_21.setMinimumSize(QtCore.QSize(10, 30))
		self.label_21.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_21.setFont(font)
		self.label_21.setObjectName("label_21")
		self.label_22 = QtWidgets.QLabel(self.groupBox_2)
		self.label_22.setGeometry(QtCore.QRect(290, 30, 22, 30))
		self.label_22.setMinimumSize(QtCore.QSize(22, 30))
		self.label_22.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_22.setFont(font)
		self.label_22.setObjectName("label_22")
		self.remplissage_p4 = QtWidgets.QLineEdit(self.groupBox_2)
		self.remplissage_p4.setGeometry(QtCore.QRect(45, 70, 65, 24))
		self.remplissage_p4.setMinimumSize(QtCore.QSize(65, 24))
		self.remplissage_p4.setMaximumSize(QtCore.QSize(65, 24))
		self.remplissage_p4.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.remplissage_p4.setText("")
		self.remplissage_p4.setObjectName("remplissage_p4")
		self.label_171 = QtWidgets.QLabel(self.groupBox_2)
		self.label_171.setGeometry(QtCore.QRect(15, 65, 22, 30))
		self.label_171.setMinimumSize(QtCore.QSize(22, 30))
		self.label_171.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_171.setFont(font)
		self.label_171.setObjectName("label_171")
		self.label_181 = QtWidgets.QLabel(self.groupBox_2)
		self.label_181.setGeometry(QtCore.QRect(115, 65, 10, 30))
		self.label_181.setMinimumSize(QtCore.QSize(10, 30))
		self.label_181.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_181.setFont(font)
		self.label_181.setObjectName("label_181")
		self.remplissage_p5 = QtWidgets.QLineEdit(self.groupBox_2)
		self.remplissage_p5.setGeometry(QtCore.QRect(185, 70, 65, 24))
		self.remplissage_p5.setMinimumSize(QtCore.QSize(65, 24))
		self.remplissage_p5.setMaximumSize(QtCore.QSize(65, 24))
		self.remplissage_p5.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.remplissage_p5.setText("")
		self.remplissage_p5.setObjectName("remplissage_p5")
		self.label_191 = QtWidgets.QLabel(self.groupBox_2)
		self.label_191.setGeometry(QtCore.QRect(255, 65, 10, 30))
		self.label_191.setMinimumSize(QtCore.QSize(10, 30))
		self.label_191.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_191.setFont(font)
		self.label_191.setObjectName("label_191")
		self.label_201 = QtWidgets.QLabel(self.groupBox_2)
		self.label_201.setGeometry(QtCore.QRect(155, 65, 22, 30))
		self.label_201.setMinimumSize(QtCore.QSize(22, 30))
		self.label_201.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_201.setFont(font)
		self.label_201.setObjectName("label_201")
		self.remplissage_p6 = QtWidgets.QLineEdit(self.groupBox_2)
		self.remplissage_p6.setGeometry(QtCore.QRect(325, 70, 65, 24))
		self.remplissage_p6.setMinimumSize(QtCore.QSize(65, 24))
		self.remplissage_p6.setMaximumSize(QtCore.QSize(65, 24))
		self.remplissage_p6.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.remplissage_p6.setText("")
		self.remplissage_p6.setObjectName("remplissage_p6")
		self.label_211 = QtWidgets.QLabel(self.groupBox_2)
		self.label_211.setGeometry(QtCore.QRect(400, 65, 10, 30))
		self.label_211.setMinimumSize(QtCore.QSize(10, 30))
		self.label_211.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_211.setFont(font)
		self.label_211.setObjectName("label_211")
		self.label_221 = QtWidgets.QLabel(self.groupBox_2)
		self.label_221.setGeometry(QtCore.QRect(290, 65, 22, 30))
		self.label_221.setMinimumSize(QtCore.QSize(22, 30))
		self.label_221.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_221.setFont(font)
		self.label_221.setObjectName("label_221")
		self.remplissage_p7 = QtWidgets.QLineEdit(self.groupBox_2)
		self.remplissage_p7.setGeometry(QtCore.QRect(45, 105, 65, 24))
		self.remplissage_p7.setMinimumSize(QtCore.QSize(65, 24))
		self.remplissage_p7.setMaximumSize(QtCore.QSize(65, 24))
		self.remplissage_p7.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.remplissage_p7.setText("")
		self.remplissage_p7.setObjectName("remplissage_p7")
		self.label_172 = QtWidgets.QLabel(self.groupBox_2)
		self.label_172.setGeometry(QtCore.QRect(15, 100, 22, 30))
		self.label_172.setMinimumSize(QtCore.QSize(22, 30))
		self.label_172.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_172.setFont(font)
		self.label_172.setObjectName("label_172")
		self.label_182 = QtWidgets.QLabel(self.groupBox_2)
		self.label_182.setGeometry(QtCore.QRect(115, 100, 10, 30))
		self.label_182.setMinimumSize(QtCore.QSize(10, 30))
		self.label_182.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_182.setFont(font)
		self.label_182.setObjectName("label_182")
		self.remplissage_p8 = QtWidgets.QLineEdit(self.groupBox_2)
		self.remplissage_p8.setGeometry(QtCore.QRect(185, 105, 65, 24))
		self.remplissage_p8.setMinimumSize(QtCore.QSize(65, 24))
		self.remplissage_p8.setMaximumSize(QtCore.QSize(65, 24))
		self.remplissage_p8.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.remplissage_p8.setText("")
		self.remplissage_p8.setObjectName("remplissage_p8")
		self.label_192 = QtWidgets.QLabel(self.groupBox_2)
		self.label_192.setGeometry(QtCore.QRect(255, 100, 10, 30))
		self.label_192.setMinimumSize(QtCore.QSize(10, 30))
		self.label_192.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_192.setFont(font)
		self.label_192.setObjectName("label_192")
		self.label_202 = QtWidgets.QLabel(self.groupBox_2)
		self.label_202.setGeometry(QtCore.QRect(155, 100, 22, 30))
		self.label_202.setMinimumSize(QtCore.QSize(22, 30))
		self.label_202.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_202.setFont(font)
		self.label_202.setObjectName("label_202")
		self.remplissage_p9 = QtWidgets.QLineEdit(self.groupBox_2)
		self.remplissage_p9.setGeometry(QtCore.QRect(325, 105, 65, 24))
		self.remplissage_p9.setMinimumSize(QtCore.QSize(65, 24))
		self.remplissage_p9.setMaximumSize(QtCore.QSize(65, 24))
		self.remplissage_p9.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.remplissage_p9.setText("")
		self.remplissage_p9.setObjectName("remplissage_p9")
		self.label_212 = QtWidgets.QLabel(self.groupBox_2)
		self.label_212.setGeometry(QtCore.QRect(400, 100, 10, 30))
		self.label_212.setMinimumSize(QtCore.QSize(10, 30))
		self.label_212.setMaximumSize(QtCore.QSize(10, 30))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_212.setFont(font)
		self.label_212.setObjectName("label_212")
		self.label_222 = QtWidgets.QLabel(self.groupBox_2)
		self.label_222.setGeometry(QtCore.QRect(290, 100, 22, 30))
		self.label_222.setMinimumSize(QtCore.QSize(22, 30))
		self.label_222.setMaximumSize(QtCore.QSize(22, 24))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(9)
		self.label_222.setFont(font)
		self.label_222.setObjectName("label_222")	
		#plotting
		self.remplissage_graph_box = QtWidgets.QGroupBox(self.centralwidget)
		self.remplissage_graph_box.setGeometry(QtCore.QRect(200, 240, 800, 511))
		remplissage_graph = PlotCanvas(self.remplissage_graph_box, width=8, height=5.1, dpi=100)
		remplissage_toolbar = NavigationToolbar(remplissage_graph, self.remplissage_graph_box)
		remplissage_toolbar.move(80, 0)		
		self.remplissage_graph_box.setStyleSheet("border: none;\n")
		self.remplissage_ok = QtWidgets.QPushButton(self.centralwidget)
		self.remplissage_ok.clicked.connect(lambda: self.remplissage_graph_plot(remplissage_graph))
		self.remplissage_ok.setGeometry(QtCore.QRect(740, 125, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.remplissage_ok.setFont(font)
		self.remplissage_ok.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.remplissage_ok.setObjectName("remplissage_ok")
		self.remplissage_keyboard_btn = QtWidgets.QPushButton(self.centralwidget)
		self.remplissage_keyboard_btn.setGeometry(QtCore.QRect(740, 178, 100, 40))
		self.remplissage_keyboard_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		self.remplissage_keyboard_btn.setText("")
		self.remplissage_keyboard_btn.clicked.connect(self.showorhide)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/newPrefix/keyboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		self.remplissage_keyboard_btn.setIcon(icon)
		self.remplissage_keyboard_btn.setIconSize(QtCore.QSize(100, 50))
		self.remplissage_keyboard_btn.setObjectName("remplissage_keyboard_btn")
		self.remplissage_upload_btn = QtWidgets.QPushButton(self.centralwidget)
		self.remplissage_upload_btn.clicked.connect(lambda: self.from_upload(remplissage_graph, ScanLineMainWindow))
		self.remplissage_upload_btn.setGeometry(QtCore.QRect(740, 72, 100, 40))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setItalic(True)
		font.setWeight(75)
		self.remplissage_upload_btn.setFont(font)
		self.remplissage_upload_btn.setStyleSheet("background-color: #abff8d;\n"
"border-radius: 5px;")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/newPrefix/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		self.remplissage_upload_btn.setIcon(icon1)
		self.remplissage_upload_btn.setIconSize(QtCore.QSize(24, 24))
		self.remplissage_upload_btn.setObjectName("remplissage_upload_btn")
		self.remplissage_keyboard = QtWidgets.QGroupBox(self.centralwidget)
		self.remplissage_keyboard.setGeometry(QtCore.QRect(0, 0, 0, 0))
		self.remplissage_keyboard.setGeometry(QtCore.QRect(0, 0, 0, 0))
		self.remplissage_keyboard.setStyleSheet("*{\n"
"    padding: 20px;\n"
"    background-color: #ccc;\n"
"}\n"
"QPushButton {\n"
"    padding: 0px;\n"
"    background-color: #fdfdfd;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 8px;\n"
"    font: 20px \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(240, 240, 240);\n"
"}")
		self.remplissage_keyboard.setTitle("")
		self.remplissage_keyboard.setObjectName("remplissage_keyboard")
		self.numbers = QtWidgets.QGroupBox(self.remplissage_keyboard)
		self.numbers.setGeometry(QtCore.QRect(250, 2, 412, 220))
		self.numbers.setMinimumSize(QtCore.QSize(412, 220))
		self.numbers.setMaximumSize(QtCore.QSize(412, 220))
		self.numbers.setStyleSheet("border: none;")
		self.numbers.setTitle("")
		self.numbers.setObjectName("numbers")
		self.btn_7 = QtWidgets.QPushButton(self.numbers)
		self.btn_7.setGeometry(QtCore.QRect(0, 5, 100, 50))
		self.btn_7.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_7.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_7.setObjectName("btn_7")
		self.btn_8 = QtWidgets.QPushButton(self.numbers)
		self.btn_8.setGeometry(QtCore.QRect(104, 5, 100, 50))
		self.btn_8.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_8.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_8.setObjectName("btn_8")
		self.btn_9 = QtWidgets.QPushButton(self.numbers)
		self.btn_9.setGeometry(QtCore.QRect(208, 5, 100, 50))
		self.btn_9.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_9.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_9.setObjectName("btn_9")
		self.divide_btn = QtWidgets.QPushButton(self.numbers)
		self.divide_btn.setGeometry(QtCore.QRect(312, 5, 100, 50))
		self.divide_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.divide_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.divide_btn.setObjectName("divide_btn")
		self.btn_5 = QtWidgets.QPushButton(self.numbers)
		self.btn_5.setGeometry(QtCore.QRect(104, 60, 100, 50))
		self.btn_5.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_5.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_5.setObjectName("btn_5")
		self.btn_4 = QtWidgets.QPushButton(self.numbers)
		self.btn_4.setGeometry(QtCore.QRect(0, 60, 100, 50))
		self.btn_4.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_4.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_4.setObjectName("btn_4")
		self.btn_6 = QtWidgets.QPushButton(self.numbers)
		self.btn_6.setGeometry(QtCore.QRect(208, 60, 100, 50))
		self.btn_6.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_6.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_6.setObjectName("btn_6")
		self.multiply_btn = QtWidgets.QPushButton(self.numbers)
		self.multiply_btn.setGeometry(QtCore.QRect(312, 60, 100, 50))
		self.multiply_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.multiply_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.multiply_btn.setObjectName("multiply_btn")
		self.btn_2 = QtWidgets.QPushButton(self.numbers)
		self.btn_2.setGeometry(QtCore.QRect(104, 115, 100, 50))
		self.btn_2.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_2.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_2.setObjectName("btn_2")
		self.btn_1 = QtWidgets.QPushButton(self.numbers)
		self.btn_1.setGeometry(QtCore.QRect(0, 115, 100, 50))
		self.btn_1.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_1.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_1.setObjectName("btn_1")
		self.btn_3 = QtWidgets.QPushButton(self.numbers)
		self.btn_3.setGeometry(QtCore.QRect(208, 115, 100, 50))
		self.btn_3.setMinimumSize(QtCore.QSize(100, 50))
		self.btn_3.setMaximumSize(QtCore.QSize(100, 50))
		self.btn_3.setObjectName("btn_3")
		self.minus_btn = QtWidgets.QPushButton(self.numbers)
		self.minus_btn.setGeometry(QtCore.QRect(312, 115, 100, 50))
		self.minus_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.minus_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.minus_btn.setObjectName("minus_btn")
		self.btn_0 = QtWidgets.QPushButton(self.numbers)
		self.btn_0.setGeometry(QtCore.QRect(0, 170, 204, 50))
		self.btn_0.setMinimumSize(QtCore.QSize(204, 50))
		self.btn_0.setMaximumSize(QtCore.QSize(204, 50))
		self.btn_0.setObjectName("btn_0")
		self.comma_btn = QtWidgets.QPushButton(self.numbers)
		self.comma_btn.setGeometry(QtCore.QRect(208, 170, 100, 50))
		self.comma_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.comma_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.comma_btn.setObjectName("comma_btn")
		self.plus_btn = QtWidgets.QPushButton(self.numbers)
		self.plus_btn.setGeometry(QtCore.QRect(312, 170, 100, 50))
		self.plus_btn.setMinimumSize(QtCore.QSize(100, 50))
		self.plus_btn.setMaximumSize(QtCore.QSize(100, 50))
		self.plus_btn.setObjectName("plus_btn")
		self.characters = QtWidgets.QGroupBox(self.remplissage_keyboard)
		self.characters.setGeometry(QtCore.QRect(10, 2, 212, 220))
		self.characters.setMinimumSize(QtCore.QSize(212, 220))
		self.characters.setMaximumSize(QtCore.QSize(212, 220))
		self.characters.setStyleSheet("border: none;")
		self.characters.setTitle("")
		self.characters.setObjectName("characters")
		self.pi_btn = QtWidgets.QPushButton(self.characters)
		self.pi_btn.setGeometry(QtCore.QRect(0, 5, 104, 50))
		self.pi_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.pi_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.pi_btn.setObjectName("pi_btn")
		self.square_btn = QtWidgets.QPushButton(self.characters)
		self.square_btn.setGeometry(QtCore.QRect(108, 5, 104, 50))
		self.square_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.square_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.square_btn.setObjectName("square_btn")
		self.sqrt_btn = QtWidgets.QPushButton(self.characters)
		self.sqrt_btn.setGeometry(QtCore.QRect(0, 60, 104, 50))
		self.sqrt_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.sqrt_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.sqrt_btn.setObjectName("sqrt_btn")
		self.power_btn = QtWidgets.QPushButton(self.characters)
		self.power_btn.setGeometry(QtCore.QRect(108, 60, 104, 50))
		self.power_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.power_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.power_btn.setObjectName("power_btn")
		self.left_btn = QtWidgets.QPushButton(self.characters)
		self.left_btn.setGeometry(QtCore.QRect(0, 115, 104, 50))
		self.left_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.left_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.left_btn.setObjectName("left_btn")
		self.right_btn = QtWidgets.QPushButton(self.characters)
		self.right_btn.setGeometry(QtCore.QRect(108, 115, 104, 50))
		self.right_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.right_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.right_btn.setObjectName("right_btn")
		self.exp_btn = QtWidgets.QPushButton(self.characters)
		self.exp_btn.setGeometry(QtCore.QRect(0, 170, 104, 50))
		self.exp_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.exp_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.exp_btn.setObjectName("exp_btn")
		self.pof10_btn = QtWidgets.QPushButton(self.characters)
		self.pof10_btn.setGeometry(QtCore.QRect(108, 170, 104, 50))
		self.pof10_btn.setMinimumSize(QtCore.QSize(104, 50))
		self.pof10_btn.setMaximumSize(QtCore.QSize(104, 50))
		self.pof10_btn.setObjectName("pof10_btn")
		ScanLineMainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(ScanLineMainWindow)
		QtCore.QMetaObject.connectSlotsByName(ScanLineMainWindow)

	def retranslateUi(self, ScanLineMainWindow):
		_translate = QtCore.QCoreApplication.translate
		ScanLineMainWindow.setWindowTitle(_translate("ScanLineMainWindow", "Computer Graphics - ScanLine"))
		self.select_segment.setText(_translate("ScanLineMainWindow", "Remplissage"))
		self.select_quit.setText(_translate("ScanLineMainWindow", "Back"))
		self.remplissage_new_btn.setText(_translate("ScanLineMainWindow", "New"))
		self.label_17.setText(_translate("ScanLineMainWindow", "P1 ("))
		self.label_18.setText(_translate("ScanLineMainWindow", ")"))
		self.label_19.setText(_translate("ScanLineMainWindow", ")"))
		self.label_20.setText(_translate("ScanLineMainWindow", "P2 ("))
		self.label_21.setText(_translate("ScanLineMainWindow", ")"))
		self.label_22.setText(_translate("ScanLineMainWindow", "P3 ("))
		self.label_171.setText(_translate("ScanLineMainWindow", "P4 ("))
		self.label_181.setText(_translate("ScanLineMainWindow", ")"))
		self.label_191.setText(_translate("ScanLineMainWindow", ")"))
		self.label_201.setText(_translate("ScanLineMainWindow", "P5 ("))
		self.label_211.setText(_translate("ScanLineMainWindow", ")"))
		self.label_221.setText(_translate("ScanLineMainWindow", "P6 ("))
		self.label_172.setText(_translate("ScanLineMainWindow", "P7 ("))
		self.label_182.setText(_translate("ScanLineMainWindow", ")"))
		self.label_192.setText(_translate("ScanLineMainWindow", ")"))
		self.label_202.setText(_translate("ScanLineMainWindow", "P8 ("))
		self.label_212.setText(_translate("ScanLineMainWindow", ")"))
		self.label_222.setText(_translate("ScanLineMainWindow", "P9 ("))
		self.remplissage_ok.setText(_translate("ScanLineMainWindow", "OK"))
		self.remplissage_upload_btn.setText(_translate("ScanLineMainWindow", "Upload"))
		self.btn_7.setText(_translate("ScanLineMainWindow", "7"))
		self.btn_7.clicked.connect(lambda: self.toinput('7'))
		self.btn_8.setText(_translate("ScanLineMainWindow", "8"))
		self.btn_8.clicked.connect(lambda: self.toinput('8'))
		self.btn_9.setText(_translate("ScanLineMainWindow", "9"))
		self.btn_9.clicked.connect(lambda: self.toinput('9'))
		self.divide_btn.setText(_translate("ScanLineMainWindow", "/"))
		self.divide_btn.clicked.connect(lambda: self.toinput('/'))
		self.btn_5.setText(_translate("ScanLineMainWindow", "5"))
		self.btn_5.clicked.connect(lambda: self.toinput('5'))
		self.btn_4.setText(_translate("ScanLineMainWindow", "4"))
		self.btn_4.clicked.connect(lambda: self.toinput('4'))
		self.btn_6.setText(_translate("ScanLineMainWindow", "6"))
		self.btn_6.clicked.connect(lambda: self.toinput('6'))
		self.multiply_btn.setText(_translate("ScanLineMainWindow", "x"))
		self.multiply_btn.clicked.connect(lambda: self.toinput('*'))
		self.btn_2.setText(_translate("ScanLineMainWindow", "2"))
		self.btn_2.clicked.connect(lambda: self.toinput('2'))
		self.btn_1.setText(_translate("ScanLineMainWindow", "1"))
		self.btn_1.clicked.connect(lambda: self.toinput('1'))
		self.btn_3.setText(_translate("ScanLineMainWindow", "3"))
		self.btn_3.clicked.connect(lambda: self.toinput('3'))
		self.minus_btn.setText(_translate("ScanLineMainWindow", "-"))
		self.minus_btn.clicked.connect(lambda: self.toinput('-'))
		self.btn_0.setText(_translate("ScanLineMainWindow", "0"))
		self.btn_0.clicked.connect(lambda: self.toinput('0'))
		self.comma_btn.setText(_translate("ScanLineMainWindow", "."))
		self.comma_btn.clicked.connect(lambda: self.toinput('.'))
		self.plus_btn.setText(_translate("ScanLineMainWindow", "+"))
		self.plus_btn.clicked.connect(lambda: self.toinput('+'))
		self.pi_btn.setText(_translate("ScanLineMainWindow", "π"))
		self.pi_btn.clicked.connect(lambda: self.toinput('π'))
		self.square_btn.setText(_translate("ScanLineMainWindow", "a²"))
		self.square_btn.clicked.connect(lambda: self.toinput('^2'))
		self.sqrt_btn.setText(_translate("ScanLineMainWindow", "√"))
		self.sqrt_btn.clicked.connect(lambda: self.toinput('sqrt('))
		self.power_btn.setText(_translate("ScanLineMainWindow", "aⁿ"))
		self.power_btn.clicked.connect(lambda: self.toinput('^'))
		self.left_btn.setText(_translate("ScanLineMainWindow", "("))
		self.left_btn.clicked.connect(lambda: self.toinput('('))
		self.right_btn.setText(_translate("ScanLineMainWindow", ")"))
		self.right_btn.clicked.connect(lambda: self.toinput(')'))
		self.exp_btn.setText(_translate("ScanLineMainWindow", "eⁿ"))
		self.exp_btn.clicked.connect(lambda: self.toinput('exp('))
		self.pof10_btn.setText(_translate("ScanLineMainWindow", "10ⁿ"))
		self.pof10_btn.clicked.connect(lambda: self.toinput('10^'))

	def showorhide(self):
		if self.remplissage_keyboard.height() == 0:
			self.remplissage_keyboard.setGeometry(QtCore.QRect(267, 230, 680, 227))
			self.remplissage_keyboard.setMinimumSize(QtCore.QSize(680, 227))
			self.remplissage_keyboard.setMaximumSize(QtCore.QSize(680, 227))
		else:
			self.remplissage_keyboard.setMinimumSize(QtCore.QSize(0, 0))
			self.remplissage_keyboard.setMaximumSize(QtCore.QSize(0, 0))
			self.remplissage_keyboard.setGeometry(QtCore.QRect(0, 0, 0, 0))

	def setFocusOnLast(self):
		widget = QtWidgets.QApplication.instance().inputFocusWidget()
		if widget:
			return widget	

	def toinput(self, text):
		widget_input = self.setFocusOnLast()
		if widget_input is None:
			widget_input = self.remplissage_p1
		widget_input.setFocus()
		self.input_value(text, widget_input)

	def input_value(self, v, input):
		input.setText(input.text()[:input.cursorPosition()] + v + input.text()[input.cursorPosition():]) 

	def clear_all_inputs(self):
		listsMyQLineEdit = self.centralwidget.findChildren(QLineEdit)
		for myQLineEdit in listsMyQLineEdit:
		    myQLineEdit.clear()

	def missing_data_dialog(self, text):
		msg = QMessageBox()
		msg.setIcon(QMessageBox.Warning)
		msg.setText(f"Entrer {text}!!")
		msg.setWindowTitle("Error!")
		msg.setStandardButtons(QMessageBox.Ok)
		msg.exec_()

	def wrong_expr_dialog(self, text):
		msg = QMessageBox()
		msg.setIcon(QMessageBox.Warning)
		msg.setText(f"Expression de {text} est fausse!!")
		msg.setWindowTitle("Error!")
		msg.setStandardButtons(QMessageBox.Ok)
		msg.exec_()

	def normalize_formula(self, formula, text):
		formula =  formula.split(',')
		formula = [formula[i].replace('^', '**').replace('π', 'pi') for i in [0,1]]
		formula  = tuple(formula)
		try:
			formula = [eval(formula[i]) for i in [0,1]]
			formula = tuple(formula)
		except Exception:
			self.wrong_expr_dialog(text)
			return None
		return formula

	def from_upload(self, remplissage_graph, ScanLineMainWindow):
		options = QFileDialog.Options()
		options |= QFileDialog.DontUseNativeDialog
		fileName, _ = QFileDialog.getOpenFileName(ScanLineMainWindow,"QFileDialog.getOpenFileName()", "","CSV Files (*.csv)", options=options)
		if fileName:
			poly = generate_from_file(fileName)
			poly_data = filling(poly)
			remplissage_graph.plot_poly(poly, poly_data)
			
	def remplissage_graph_plot(self, remplissage_graph):
		p1, p2, p3 = self.remplissage_p1.text(), self.remplissage_p2.text(), self.remplissage_p3.text()
		p4, p5, p6 = self.remplissage_p4.text(), self.remplissage_p5.text(), self.remplissage_p6.text()
		p7, p8, p9 = self.remplissage_p7.text(), self.remplissage_p8.text(), self.remplissage_p9.text()
		if (len(p1) == 0) or (len(p2) == 0) or (len(p3) == 0) :
			self.missing_data_dialog('au moins P1, P2, et P3')
			return
		points = [p1, p2, p3, p4, p5, p6, p7, p8, p9]
		i = 0
		while i < 9 and len(points[i]) > 0:
			points[i] = self.normalize_formula(points[i], f'p{i+1}')
			i += 1
		if i < 9:
			points = points[:i]
		test = 1
		for j in range(i):
			if points[j] == None:
				test = 0
				break
		if (test):
			self.remplissage_keyboard.setMinimumSize(QtCore.QSize(680, 227))
			self.showorhide()
			poly = points
			poly_data = filling(poly)
			remplissage_graph.plot_poly(poly, poly_data)
import resources


if __name__ == "__main__":
	import sys
	app = MyApplication(sys.argv)
	ScanLineMainWindow = QtWidgets.QMainWindow()
	ui = Ui_ScanLineMainWindow()
	ui.setupUi(ScanLineMainWindow)
	ScanLineMainWindow.show()
	sys.exit(app.exec_())
